// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Public types for @viberevert/reporters' fix-prompt-rendering surface
// (M E Step 2). Mirror of receipt-types.ts's ReceiptRenderInput pattern,
// scoped to the ReportFile artifact and to a text-only renderer.
//
// =============================================================================
// Locked design (per M E plan Step 2 + D45 + contract D80-D97)
// =============================================================================
//
//   - **Text-only renderer (v0.7.0).** Unlike the M C report and M D
//     receipt surfaces (each with a three-format dispatcher: terminal /
//     markdown / json), the fix-prompt renderer exposes ONE function
//     returning ONE string. There is no `FixPromptFormat` union, no
//     dispatcher, no `--json` / `--markdown` flags on the CLI. The
//     prompt is meant to be pasted into a coding agent; format wrappers
//     would add friction with no v0.7.0 consumer. See contract D81 /
//     D87 / D97 for the deferred-evolution path (when MCP
//     generate_fix_prompt lands, a structured envelope + format
//     dispatcher can be added additively without breaking the v0.7.0
//     text-only contract).
//
//   - `productVersion` is REQUIRED for the same D29 dep-direction
//     reason as `RenderInput.productVersion` and
//     `ReceiptRenderInput.productVersion`: reporters MUST NOT reach
//     back into the CLI's package.json to discover the running version.
//     The CLI resolves the version (via `resolveProductVersionForReport`)
//     and passes the string in. The fix-prompt renderer uses it in the
//     locked three-line footer per contract D85.9 ("Generated by
//     VibeRevert v<version>" line). Keeping the input shape uniform
//     across reporter surfaces — even though prompt-fix has only one
//     "format" — means CLI dispatch code doesn't branch on surface
//     when assembling renderer input.
//
//   - All types come from @viberevert/session-format. Reporters owns
//     NO schema definitions of its own and NEVER reaches into deeper
//     session-format modules (per the locked public-API rule of
//     session-format).
//
//   - No threshold field. Same reason as receipt-types.ts: the prompt
//     is not a noise-budgeted output. Truncation (max 20 findings) is
//     deterministic and locked at the template layer (D85.5), not a
//     caller-tunable filter. Adding a threshold input would invite the
//     wrong mental model.
//
//   - No `sessionTask` field, even though the contract's D85.3 allows
//     an optional `Task:` line. The plan locks (per user item 10) that
//     task context comes from ReportFile metadata only, NOT from
//     loading session.json. If the current ReportFileSchema does not
//     carry task (v0.7.0 it does not), the renderer omits the Task
//     section entirely. A future ReportFileSchema extension that adds
//     task is auto-picked-up via the existing `file` input; no input
//     shape change required.

import type { ReportFile } from "@viberevert/session-format";

// =============================================================================
// FixPromptRenderInput
// =============================================================================

/**
 * Single argument shape for the fix-prompt renderer. Mirrors
 * `ReceiptRenderInput` (file + productVersion) — same two fields,
 * different artifact type.
 *
 * `file` is the loaded `ReportFile` (the on-disk wrapper as persisted
 * by `viberevert check` to either `.viberevert/sessions/<sess>/report.json`
 * or `.viberevert/reports/<rpt>/report.json` per D26). The renderer
 * branches on `file.kind` for the source-attribution line's
 * `since_kind` reference and for the suggested-next-steps section's
 * session-bound vs ad-hoc variant (per contract D85.6).
 *
 * `productVersion` is REQUIRED. See file header lock #2 for the D29
 * rationale. Used by the renderer in the footer's
 * `Generated by VibeRevert v<version>` line (D85.9).
 *
 * No threshold. No sessionTask. The renderer is text-only, deterministic,
 * and consumes ONLY this input — no clock reads, no random reads, no
 * second I/O dependency.
 */
export interface FixPromptRenderInput {
  readonly file: ReportFile;
  readonly productVersion: string;
}
