// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// renderMarkdown: CommonMark-only rendering of a ReportFile for
// human-readable markdown viewers / PR descriptions / issue bodies.
//
// =============================================================================
// CONTRACT (D45 + D38 + D54)
// =============================================================================
//
// Output is:
//   - PURE STRING — caller (CLI) writes to stdout; reporters never
//     write to terminal streams per D29.
//   - COMMONMARK ONLY — no GFM extensions, no HTML, no tables.
//     CommonMark proper has no table syntax; GFM tables (including
//     the colon-alignment variants) are explicitly forbidden per
//     D45. Headings, lists, fenced code blocks, and emphasis only.
//   - DETERMINISTIC — locked layout structure drives golden-fixture
//     stability from Step 10. Any future layout change requires a
//     deliberate `pnpm regen-goldens` run + commit.
//   - INJECTION-SAFE — user-derived text (task, titles, messages,
//     paths, tags, etc.) is run through `inlineMarkdown` before
//     placement in the rendered output. Evidence content is wrapped
//     in a fenced code block with a DYNAMIC-LENGTH fence so embedded
//     backticks cannot break out.
//   - NEWLINE-TERMINATED — the final character is always '\n'.
//
// =============================================================================
// LAYOUT (LOCKED — drives golden fixtures from Step 10)
// =============================================================================
//
//   # VibeRevert Report
//
//   ## Summary
//
//   - **Report ID:** <id>
//   - **Kind:** <kind>
//   - **Since:** <ref> (kind: <since_kind>)
//   - **Resolved SHA:** <sha>
//   - **Written at:** <iso>
//   - **Staged-only:** true                  [only when present]
//   - **Task:** <task>                       [only when present]
//   - **Frameworks:** <comma-separated, or "(none)">
//   - **Risk Level:** <UPPERCASE>
//   - **Summary:** <summary>                 [only when present]
//
//   ## Findings
//
//   No findings.                             [when results empty]
//
//   ### <category> (<N> findings)            [one H3 per category, ASCII-sorted]
//
//   **[LEVEL]** <title> (<category>, <confidence>)
//
//   <message paragraph>
//
//   ```                                       [fence length: dynamic]
//   File: <path>[:<line>]
//   Command: <command>                       [when evidence.command present]
//   Detail: <detail>
//   ```
//
//   **Recommendation:** <reco>               [when present]
//
//   ## Changed Files
//
//   No changed files.                        [when changed_files empty]
//
//   - `<S>` <path> — <tags-csv-or-"(no tags)"> — <LEVEL> [(was: <previous-path>)]
//
//   Generated by VibeRevert v<version>.
//
// Status codes (S): A = added, M = modified, D = deleted,
// R = renamed, T = type_changed.
//
// Category H3 ordering: explicitly ASCII-sorted by category key.
// The engine's sort key `[level desc, category asc, id asc, ...]`
// has level FIRST, so a category can appear in multiple separated
// runs of engine output (e.g., critical/payments, high/auth,
// high/payments — payments is not contiguous). The Map-based
// grouping handles this correctly; the explicit category sort makes
// the H3 sequence deterministic and intuitive for human readers.
// Within a category, findings preserve their relative engine order.

import type { ChangedFile, CheckResult, Evidence, ReportFile } from "@viberevert/session-format";

import { applyThreshold } from "./threshold.js";
import type { RenderInput } from "./types.js";

// =============================================================================
// Status codes (mirrors terminal.ts — same git-porcelain set)
// =============================================================================

const STATUS_CODES: Readonly<Record<string, string>> = {
  added: "A",
  modified: "M",
  deleted: "D",
  renamed: "R",
  type_changed: "T",
};

function statusCode(status: string): string {
  return STATUS_CODES[status] ?? "?";
}

// =============================================================================
// Escaping + fencing helpers
// =============================================================================

/**
 * Escape a string for safe inline placement inside a markdown
 * paragraph, bullet, heading, or emphasis context. Handles:
 *   - Newlines → space (prevents paragraph splits + block-level
 *     re-parsing on subsequent lines).
 *   - Backslash → `\\` (MUST be escaped first; later escapes add
 *     backslashes that must not be doubled).
 *   - Backtick, asterisk, underscore, brackets → backslash-prefixed
 *     (prevents inline code, emphasis, and link formation).
 *   - `<` / `>` → HTML entities (prevents raw-HTML injection per
 *     the no-HTML D45 lock).
 *
 * Known limitation: does NOT escape leading block-level characters
 * (`#`, `-`, `>`, `+`, `1.`, etc.). When the escaped value is
 * placed mid-line (e.g., after `**Label:**`), this is fine — block
 * constructs only trigger at line start. The message paragraph is
 * the one place where escaped content sits at start-of-line; no
 * current M C detector produces messages beginning with block-level
 * chars, so the risk is accepted and documented. If future detectors
 * produce such messages, extend this helper or wrap the message in
 * a list/blockquote.
 */
function inlineMarkdown(text: string): string {
  return text
    .replace(/\r?\n/g, " ")
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Return the length of the longest run of backtick characters in
 * `text`. Used by `buildFencedBlock` to pick a fence length safely.
 */
function maxBacktickRun(text: string): number {
  let max = 0;
  let current = 0;

  for (const ch of text) {
    if (ch === "`") {
      current++;
      if (current > max) max = current;
    } else {
      current = 0;
    }
  }

  return max;
}

/**
 * Wrap `lines` in a fenced code block whose fence is longer than
 * any backtick run inside (per CommonMark §4.5). Fence is the
 * larger of 3 and `maxRun + 1`. The contents are returned verbatim
 * (no escaping needed inside fenced code blocks).
 */
function buildFencedBlock(lines: readonly string[]): string[] {
  const maxRun = Math.max(0, ...lines.map(maxBacktickRun));
  const fence = "`".repeat(Math.max(3, maxRun + 1));
  return [fence, ...lines, fence];
}

// =============================================================================
// Section builders
// =============================================================================

function buildSummaryBullets(file: ReportFile): string[] {
  const lines: string[] = [];
  lines.push(`- **Report ID:** ${inlineMarkdown(file.report_id)}`);
  lines.push(`- **Kind:** ${inlineMarkdown(file.kind)}`);
  lines.push(
    `- **Since:** ${inlineMarkdown(file.since_ref)} (kind: ${inlineMarkdown(file.since_kind)})`,
  );
  lines.push(`- **Resolved SHA:** ${inlineMarkdown(file.since_resolved_sha)}`);
  lines.push(`- **Written at:** ${inlineMarkdown(file.written_at)}`);
  if (file.staged_only === true) {
    lines.push("- **Staged-only:** true");
  }
  if (file.report.task !== undefined) {
    lines.push(`- **Task:** ${inlineMarkdown(file.report.task)}`);
  }
  const frameworks =
    file.report.detected_frameworks.length === 0
      ? "(none)"
      : file.report.detected_frameworks.map(inlineMarkdown).join(", ");
  lines.push(`- **Frameworks:** ${frameworks}`);
  lines.push(`- **Risk Level:** ${inlineMarkdown(file.report.risk_level.toUpperCase())}`);
  if (file.report.summary !== undefined) {
    lines.push(`- **Summary:** ${inlineMarkdown(file.report.summary)}`);
  }
  return lines;
}

function buildEvidenceLines(evidence: readonly Evidence[]): string[] {
  const lines: string[] = [];
  for (const [i, ev] of evidence.entries()) {
    if (i > 0) lines.push("");
    if (ev.file !== undefined) {
      const path = ev.line !== undefined ? `${ev.file}:${ev.line}` : ev.file;
      lines.push(`File: ${path}`);
    }
    if (ev.command !== undefined) {
      lines.push(`Command: ${ev.command}`);
    }
    lines.push(`Detail: ${ev.detail}`);
  }
  return lines;
}

function buildFinding(result: CheckResult): string[] {
  const lines: string[] = [];
  // Locked per D45: **[LEVEL]** title (category, confidence)
  lines.push(
    `**[${inlineMarkdown(result.level.toUpperCase())}]** ${inlineMarkdown(result.title)} (${inlineMarkdown(result.category)}, ${inlineMarkdown(result.confidence)})`,
  );
  lines.push("");
  lines.push(inlineMarkdown(result.message));
  lines.push("");
  // Evidence content goes UNESCAPED inside the dynamic-length fence —
  // the fence handles embedded backticks, and other markdown chars
  // are inert inside fenced code blocks.
  for (const line of buildFencedBlock(buildEvidenceLines(result.evidence))) {
    lines.push(line);
  }
  if (result.recommendation !== undefined && result.recommendation.length > 0) {
    lines.push("");
    lines.push(`**Recommendation:** ${inlineMarkdown(result.recommendation)}`);
  }
  return lines;
}

/**
 * Group results by category in a single pass. This does NOT rely on
 * same-category findings being contiguous in engine order: the engine
 * sort key starts with level desc, so a category can appear in
 * multiple separated runs (e.g., critical/payments before high/auth
 * before high/payments).
 *
 * The caller explicitly sorts the returned Map's keys for
 * alphabetical H3 ordering. Within each category, findings preserve
 * their relative engine order.
 */
function groupByCategory(results: readonly CheckResult[]): Map<string, readonly CheckResult[]> {
  const groups = new Map<string, CheckResult[]>();
  for (const r of results) {
    let arr = groups.get(r.category);
    if (arr === undefined) {
      arr = [];
      groups.set(r.category, arr);
    }
    arr.push(r);
  }
  return groups;
}

function buildFindingsSection(results: readonly CheckResult[]): string[] {
  const lines: string[] = [];
  lines.push("## Findings");
  lines.push("");
  if (results.length === 0) {
    lines.push("No findings.");
    return lines;
  }

  const groups = groupByCategory(results);
  // Explicit ASCII-asc category sort — see groupByCategory's JSDoc
  // for why first-seen order is NOT alphabetical.
  const categories = [...groups.keys()].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

  let firstGroup = true;
  for (const category of categories) {
    const findings = groups.get(category);
    if (findings === undefined) continue; // defensive; impossible by construction

    if (!firstGroup) lines.push("");
    firstGroup = false;

    const noun = findings.length === 1 ? "finding" : "findings";
    lines.push(`### ${inlineMarkdown(category)} (${findings.length} ${noun})`);
    lines.push("");

    for (const [i, f] of findings.entries()) {
      if (i > 0) lines.push("");
      for (const line of buildFinding(f)) {
        lines.push(line);
      }
    }
  }
  return lines;
}

function buildChangedFileBullet(cf: ChangedFile): string {
  const tags =
    cf.risk_tags.length === 0 ? "(no tags)" : cf.risk_tags.map(inlineMarkdown).join(", ");
  const level = inlineMarkdown(cf.risk_level.toUpperCase());
  const base = `- \`${statusCode(cf.status)}\` ${inlineMarkdown(cf.path)} — ${tags} — ${level}`;
  if (cf.status === "renamed" && cf.previous_path !== undefined) {
    return `${base} (was: ${inlineMarkdown(cf.previous_path)})`;
  }
  return base;
}

function buildChangedFilesSection(changedFiles: readonly ChangedFile[]): string[] {
  const lines: string[] = [];
  lines.push("## Changed Files");
  lines.push("");
  if (changedFiles.length === 0) {
    lines.push("No changed files.");
    return lines;
  }
  for (const cf of changedFiles) {
    lines.push(buildChangedFileBullet(cf));
  }
  return lines;
}

// =============================================================================
// renderMarkdown
// =============================================================================

/**
 * Render a ReportFile as CommonMark suitable for PR descriptions,
 * issue tracker comments, etc. Applies `input.threshold` per D38
 * before formatting. The output is newline-terminated.
 *
 * Uses `input.productVersion` for the locked footer "Generated by
 * VibeRevert v<version>." (D45 markdown lock). The footer is a
 * paragraph (not a heading) and ends with a period.
 *
 * Pure synchronous: no I/O, no Date.now(), no Math.random().
 *
 * The caller (CLI) is responsible for writing the returned string
 * to stdout per the D29 boundary — reporters never write to
 * terminal streams.
 */
export function renderMarkdown(input: RenderInput): string {
  const file = applyThreshold(input.file, input.threshold);

  const sections: string[][] = [
    ["# VibeRevert Report"],
    [""],
    ["## Summary"],
    [""],
    buildSummaryBullets(file),
    [""],
    buildFindingsSection(file.report.results),
    [""],
    buildChangedFilesSection(file.report.changed_files),
    [""],
    [`Generated by VibeRevert v${inlineMarkdown(input.productVersion)}.`],
  ];

  return `${sections.flat().join("\n")}\n`;
}
