// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Public types for @viberevert/reporters' receipt-rendering surface
// (M D Step 5). Mirror of types.ts's RenderInput pattern, scoped to
// the ReceiptFile artifact instead of ReportFile.
//
// =============================================================================
// Locked design (per M D plan Step 5 + D45)
// =============================================================================
//
//   - Reuses `ReporterFormat` from types.ts. The three output
//     formats (terminal / json / markdown) are identical between
//     the M C report surface and the M D receipt surface; both
//     target the same human/machine consumers and the CLI's
//     `--json` / `--markdown` flags route to the same format
//     dispatch on both surfaces. A future receipt-only format
//     (none foreseen in M D) would require adding the variant to
//     `ReporterFormat` AND the receipt dispatcher — same touch
//     points the report dispatcher already covers.
//
//   - NO threshold-filter field. Receipts describe the outcomes of
//     a single rollback operation; the `results[]` and `failures[]`
//     arrays are inherently bounded by what `restoreCheckpoint`
//     actually did. There's no "noisy findings to suppress"
//     equivalent the way M C reports have noise-budget caps over
//     `results[]`. Adding threshold would invite the wrong mental
//     model — receipts are exhaustive transactional records, not
//     summaries.
//
//   - `productVersion` is REQUIRED for the same reason as
//     `RenderInput.productVersion`: reporters MUST NOT reach back
//     into the CLI's package.json to discover the running version
//     per D29's dep-direction rule. The CLI resolves the version
//     (via `resolveProductVersionForReport`) and passes the string
//     in. Markdown uses it for the locked footer ("Generated by
//     VibeRevert v<version>"); other renderers may accept it
//     without using it — keeping the input shape uniform across
//     formats means CLI dispatch code doesn't branch on format
//     when assembling renderer input.
//
//   - All types come from @viberevert/session-format. Reporters
//     owns NO schema definitions of its own and NEVER reaches into
//     deeper session-format modules (per the locked public-API
//     rule of session-format).

import type { ReceiptFile } from "@viberevert/session-format";

// =============================================================================
// ReceiptRenderInput
// =============================================================================

/**
 * Single argument shape for every receipt renderer. Mirrors
 * `RenderInput` (file + productVersion) without the `threshold` field.
 *
 * `file` is the on-disk `ReceiptFile` wrapper as persisted by the
 * rollback CLI per D68 — either `rollback-receipt.json` (--apply mode)
 * or `rollback-dry-run-receipt.json` (default dry-run mode). The
 * renderers branch on `file.mode` for mode-specific copy (dry-run
 * banner, "would restore" vs "restored" past-tense, etc.); the
 * underlying schema is identical across both files per D69.
 *
 * `productVersion` is REQUIRED. See file header lock #3 for the
 * D29 rationale.
 *
 * IMPORTANT for the JSON renderer (per the M D Step 5 lock): the
 * JSON output MUST stay strictly schema-verbatim — emit the
 * `ReceiptFile` value untouched and DO NOT include `productVersion`
 * in the serialized output. `productVersion` is rendering metadata
 * for the markdown footer, NOT a schema field. Adding it to JSON
 * would break the D38 schema-verbatim contract and silently mutate
 * a persisted-artifact-shaped wire output.
 */
export interface ReceiptRenderInput {
  readonly file: ReceiptFile;
  readonly productVersion: string;
}
