// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// renderReceiptMarkdown: CommonMark-only rendering of a ReceiptFile
// for human-readable markdown viewers / PR descriptions / issue
// bodies.
//
// =============================================================================
// CONTRACT (D45 + D54 + D62)
// =============================================================================
//
// Output is:
//   - PURE STRING — caller (CLI) writes to stdout; reporters never
//     write to terminal streams per D29.
//   - COMMONMARK ONLY — no GFM extensions, no HTML, no tables, no
//     GitHub-flavored alert syntax (`> [!WARNING]`). Headings, lists,
//     fenced code blocks, blockquotes, inline-code spans, and
//     emphasis only. Same locked surface as the M C
//     `renderMarkdown` per D45.
//   - DETERMINISTIC — locked layout drives golden-fixture stability
//     from Step 8. Any future layout change requires a deliberate
//     `pnpm regen-goldens` run + commit.
//   - INJECTION-SAFE — user-derived text uses one of THREE escape
//     helpers based on context:
//       * `inlineMarkdown` for prose / labels / messages / reasons /
//         footer version / out-of-scope notice — escapes backslash,
//         backtick, asterisk, underscore, brackets, and HTML-encodes
//         angle brackets. Safe for placement inside paragraphs,
//         bullets, headings, and blockquotes.
//       * `inlineCode` for identifiers and paths rendered as code
//         spans — uses a DYNAMIC-LENGTH backtick fence (per
//         CommonMark §6.1) longer than any backtick run in the
//         content, plus leading/trailing space padding when the
//         content begins or ends with a backtick or space. NEVER
//         compose with `inlineMarkdown` — code-span escape rules
//         do not honor backslash escapes, so the two helpers
//         must be used independently on RAW input.
//       * `schemaToken` for schema-controlled enum values (mode,
//         dirty_tree_check, outcome, error_code) — emits the
//         value VERBATIM when it matches the safe alphanumeric-
//         and-underscore shape `/^[A-Za-z0-9_]+$/`, falling back
//         to `inlineMarkdown` escaping for any value outside that
//         set. Today's locked schema values all match the safe
//         shape, so the helper emits them verbatim — preserving
//         snake_case grep-ability that `inlineMarkdown` would
//         destroy by escaping underscores ("TRACKED\_RESTORED").
//         A future schema bump introducing markdown-active
//         characters in a token would automatically fall back
//         to safe escaping without a renderer touch-up.
//   - NEWLINE-TERMINATED — the final character is always '\n'.
//
// =============================================================================
// LAYOUT (LOCKED — drives golden fixtures from Step 8)
// =============================================================================
//
//   # VibeRevert Rollback Receipt                     [or "...Receipt (Dry-Run)"]
//
//   ## Summary
//
//   - **Rollback ID:** `<rb_id>`                      [inlineCode; dynamic fence]
//   - **Session ID:** `<sess_id>`
//   - **Checkpoint ID:** `<cp_id>`
//   - **Mode:** <dry_run | apply>                     [schemaToken; verbatim]
//   - **Forced:** <true | false>
//   - **Pre-rollback CP:** `<cp_id>` | (none - dry-run)
//   - **Dirty-tree check:** <performed | skipped_no_after_state>   [schemaToken]
//   - **Written at:** <iso>
//
//   > **Warning:** Active session - apply mode would refuse on this session.   [iff present]
//
//   > **Warning:** No machine-readable after-status snapshot for this session. [iff present]
//
//   ## Forced Unrelated Dirty Paths                   [SECTION OMITTED when empty]
//
//   - `<path>`
//   - `<path>`
//
//   ## Results
//
//   No results.                                       [when results empty]
//
//   - **[<OUTCOME>]** `<path>`                        [bracketToken / inlineCode]
//     - Reason: <reason>                              [iff present; inlineMarkdown]
//
//   ## Failures
//
//   No failures.                                      [when failures empty]
//
//   - **[<ERROR_CODE>]** <message>                    [bracketToken / inlineMarkdown]
//     - Affected paths:                               [iff affected_paths non-empty]
//       - `<path>`                                    [inlineCode]
//
//   ## Out of Scope
//
//   <inlineMarkdown(file.out_of_scope_notice)>        [escaped single paragraph]
//
//   Generated by VibeRevert v<version>.
//
// Banner casing intentionally diverges from terminal: markdown uses
// `(Dry-Run)` (title-case heading qualifier reads naturally in
// rendered markdown) while terminal uses `(DRY-RUN)` (uppercase
// matches the bracket-token convention in terminal output). Both
// communicate the same signal in their own idiom.
//
// Warnings are blockquote paragraphs rather than an H2 section.
// CommonMark blockquotes are the idiomatic "alert" container; an
// H2 "Warnings" section that's empty on most receipts would create
// awkward layout. Consecutive warnings are separated by a blank
// line so each renders as a DISTINCT blockquote block per
// CommonMark §5.1 (two adjacent `>` lines without a blank line
// between them form ONE blockquote block, which would visually
// merge the two warnings into one wrapped paragraph in most
// renderers).
//
// "Forced Unrelated Dirty Paths" section is omitted entirely when
// empty (same lock as terminal — see file header in
// receipt-terminal.ts).
//
// Results / Failures use bulleted lists with sub-bullets for
// reasons / affected paths. Denser than the terminal's
// dividered-section layout but appropriate for markdown's
// hierarchical syntax — each entry is one top-level bullet, with
// optional sub-bullets for detail.
//
// Outcome / error_code tokens preserve the schema's snake_case form
// uppercased inside brackets ("[TRACKED_RESTORED]",
// "[EXTRACTION_CONFLICT]") via `bracketToken` (`schemaToken` +
// bracket wrap) and wrapped in bold emphasis
// ("**[TRACKED_RESTORED]**"). Underscores are NOT escaped —
// `schemaToken`'s safe-shape gate emits them verbatim — so the
// rendered source bytes stay grep-able as single words. Same
// bracket convention as M C's "**[LEVEL]**" finding header.
//
// Identifiers (ids, paths) are wrapped via `inlineCode` for visual
// distinction from prose AND CommonMark §6.1 safety against
// embedded backticks. Status enum values (mode, forced,
// dirty_tree_check) are NOT wrapped in code spans — they're short
// keywords that read naturally inline; `schemaToken` keeps them
// safe AND verbatim.

import type { ReceiptFile, RollbackFailure, RollbackFileResult } from "@viberevert/session-format";

import { bracketToken, inlineCode, inlineMarkdown, schemaToken } from "./markdown-escape.js";
import type { ReceiptRenderInput } from "./receipt-types.js";

// =============================================================================
// Escaping helpers
// =============================================================================
//
// M 0.8.0 step 12: the four helpers below MOVED to `markdown-escape.ts`,
// byte-for-byte, and are imported above. They were duplicated here and in
// `markdown.ts`, each with a comment telling the reader to mirror any change
// into the other, which is the shape where a fix lands in one renderer and the
// other keeps emitting unsafe output with nothing failing. The goldens are the
// proof this move changed no output.

// =============================================================================
// Section builders
// =============================================================================

function buildBanner(file: ReceiptFile): string[] {
  // Mode-suffix on the H1 so a human reading the rendered markdown
  // immediately knows whether this is a dry-run preview or an
  // applied operation. Title-case "(Dry-Run)" reads more naturally
  // as a heading qualifier than all-caps; the Mode summary bullet
  // below carries the same signal for machine readers.
  const suffix = file.mode === "dry_run" ? " (Dry-Run)" : "";
  return [`# VibeRevert Rollback Receipt${suffix}`];
}

function buildSummaryBullets(file: ReceiptFile): string[] {
  const lines: string[] = [];
  lines.push(`- **Rollback ID:** ${inlineCode(file.rollback_id)}`);
  lines.push(`- **Session ID:** ${inlineCode(file.session_id)}`);
  lines.push(`- **Checkpoint ID:** ${inlineCode(file.checkpoint_id)}`);
  lines.push(`- **Mode:** ${schemaToken(file.mode)}`);
  lines.push(`- **Forced:** ${String(file.forced)}`);
  // pre_rollback_checkpoint_id is null in dry-run mode per the D69
  // refine; render an explicit ASCII placeholder so the human
  // reader knows the absence is intentional, not missing data.
  // Match the terminal placeholder text byte-for-byte for
  // cross-format consistency.
  const preRollbackCp =
    file.pre_rollback_checkpoint_id !== null
      ? inlineCode(file.pre_rollback_checkpoint_id)
      : "(none - dry-run)";
  lines.push(`- **Pre-rollback CP:** ${preRollbackCp}`);
  lines.push(`- **Dirty-tree check:** ${schemaToken(file.dirty_tree_check)}`);
  lines.push(`- **Written at:** ${inlineMarkdown(file.written_at)}`);
  return lines;
}

function buildWarnings(file: ReceiptFile): string[] {
  const lines: string[] = [];
  // Consecutive warnings are separated by a blank line so each
  // renders as a distinct blockquote block per CommonMark §5.1.
  // The `if (lines.length > 0)` guard is a no-op on the first
  // emission and inserts the blank-separator on every subsequent
  // emission — uniform pattern so adding a third warning later
  // requires no logic change here.
  if (file.active_session_warning === true) {
    if (lines.length > 0) lines.push("");
    // Wording assumes mode === "dry_run". The D69 schema refine
    // `r.active_session_warning !== true || r.mode === "dry_run"`
    // guarantees this is safe — apply mode refuses active sessions
    // outright per D63 and never produces a receipt with this
    // warning. If that refine is ever relaxed, this wording must
    // become mode-neutral.
    lines.push("> **Warning:** Active session - apply mode would refuse on this session.");
  }
  if (file.un_ended_session_warning === true) {
    if (lines.length > 0) lines.push("");
    // Mode-neutral: un_ended_session_warning can appear on BOTH
    // dry-run receipts (informational) AND apply-with-force
    // receipts (escape hatch fired) per the D69 coupling refine.
    lines.push("> **Warning:** No machine-readable after-status snapshot for this session.");
  }
  return lines;
}

function buildForcedUnrelatedDirtyPathsSection(paths: readonly string[]): string[] {
  // Section omitted entirely when empty (per layout lock above).
  if (paths.length === 0) return [];
  const lines: string[] = [];
  lines.push("## Forced Unrelated Dirty Paths");
  lines.push("");
  for (const path of paths) {
    lines.push(`- ${inlineCode(path)}`);
  }
  return lines;
}

function buildResult(result: RollbackFileResult): string[] {
  const lines: string[] = [];
  lines.push(`- **${bracketToken(result.outcome)}** ${inlineCode(result.path)}`);
  if (result.reason !== undefined && result.reason.length > 0) {
    // Sub-bullet under the result entry. Two-space indent per
    // CommonMark §5.2 (loose list item continuation).
    lines.push(`  - Reason: ${inlineMarkdown(result.reason)}`);
  }
  return lines;
}

function buildResultsSection(results: readonly RollbackFileResult[]): string[] {
  const lines: string[] = [];
  lines.push("## Results");
  lines.push("");
  if (results.length === 0) {
    lines.push("No results.");
    return lines;
  }
  for (const result of results) {
    for (const line of buildResult(result)) {
      lines.push(line);
    }
  }
  return lines;
}

function buildFailure(failure: RollbackFailure): string[] {
  const lines: string[] = [];
  lines.push(`- **${bracketToken(failure.error_code)}** ${inlineMarkdown(failure.message)}`);
  if (failure.affected_paths.length > 0) {
    // Sub-bullet ("Affected paths:") with nested sub-sub-bullets
    // for each path. Four-space indent for the inner list per
    // CommonMark nesting rules.
    lines.push("  - Affected paths:");
    for (const path of failure.affected_paths) {
      lines.push(`    - ${inlineCode(path)}`);
    }
  }
  return lines;
}

function buildFailuresSection(failures: readonly RollbackFailure[]): string[] {
  const lines: string[] = [];
  lines.push("## Failures");
  lines.push("");
  if (failures.length === 0) {
    lines.push("No failures.");
    return lines;
  }
  for (const failure of failures) {
    for (const line of buildFailure(failure)) {
      lines.push(line);
    }
  }
  return lines;
}

function buildOutOfScopeSection(file: ReceiptFile): string[] {
  const lines: string[] = [];
  lines.push("## Out of Scope");
  lines.push("");
  // Verbatim from file.out_of_scope_notice, escaped via
  // inlineMarkdown for defense in depth. The schema's z.literal
  // refine guarantees this equals ROLLBACK_OUT_OF_SCOPE_NOTICE from
  // @viberevert/session-format; the current literal is pure ASCII
  // prose with no markdown-active characters, so escape behavior
  // is a no-op today. A future schema bump introducing markdown
  // chars in the notice would be handled correctly without a
  // renderer touch-up. Tests should assert byte-equality of the
  // rendered paragraph against `inlineMarkdown(ROLLBACK_OUT_OF_SCOPE_NOTICE)`
  // to lock the "renders exactly as the schema literal escapes to"
  // contract.
  lines.push(inlineMarkdown(file.out_of_scope_notice));
  return lines;
}

// =============================================================================
// renderReceiptMarkdown
// =============================================================================

/**
 * Render a `ReceiptFile` as CommonMark suitable for PR descriptions,
 * issue tracker comments, etc. The output is newline-terminated.
 *
 * Uses `input.productVersion` for the locked footer
 * "Generated by VibeRevert v<version>." (D45 markdown lock,
 * mirroring `renderMarkdown` for reports). The footer is a
 * paragraph (not a heading) and ends with a period; the version
 * value is escaped via `inlineMarkdown` for the same injection-
 * safety reason every other user-derived prose value is escaped.
 *
 * Pure synchronous: no I/O, no Date.now(), no Math.random(),
 * no terminal writes. Allocations are limited to local formatting
 * arrays/strings needed to build the returned output.
 *
 * The caller (CLI) is responsible for writing the returned string
 * to stdout per the D29 boundary — reporters never write to
 * terminal streams.
 */
export function renderReceiptMarkdown(input: ReceiptRenderInput): string {
  const { file } = input;

  const sections: string[][] = [
    buildBanner(file),
    [""],
    ["## Summary"],
    [""],
    buildSummaryBullets(file),
  ];

  const warnings = buildWarnings(file);
  if (warnings.length > 0) {
    sections.push([""]);
    sections.push(warnings);
  }

  const forcedUnrelated = buildForcedUnrelatedDirtyPathsSection(file.forced_unrelated_dirty_paths);
  if (forcedUnrelated.length > 0) {
    sections.push([""]);
    sections.push(forcedUnrelated);
  }

  sections.push([""]);
  sections.push(buildResultsSection(file.results));
  sections.push([""]);
  sections.push(buildFailuresSection(file.failures));
  sections.push([""]);
  sections.push(buildOutOfScopeSection(file));
  sections.push([""]);
  sections.push([`Generated by VibeRevert v${inlineMarkdown(input.productVersion)}.`]);

  return `${sections.flat().join("\n")}\n`;
}
