// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// renderSelectiveReceiptMarkdown: CommonMark for a selective rollback receipt.
//
// =============================================================================
// Contract
// =============================================================================
//
//   - PURE STRING, CommonMark only. No GFM, no HTML, no tables, no alert
//     syntax. Headings, lists, code spans and emphasis.
//   - INJECTION-SAFE. Every user-derived value goes through one of the shared
//     helpers in `markdown-escape.ts`: `inlineCode` for identifiers and paths,
//     `schemaToken` for schema enums, `inlineMarkdown` for prose. Never
//     compose two of them on one value.
//   - DETERMINISTIC, so the layout can be a golden.
//   - NEWLINE-TERMINATED, ending with the locked version footer.
//
// Exhaustive over every union in the receipt, with a `never` binding in each
// default branch. See `selective-receipt-terminal.ts` for why that matters
// here specifically: several arms exist to say the outcome could not be
// determined, and rendering one as a blank would read as "nothing happened".
//
// =============================================================================
// Layout
// =============================================================================
//
//   # VibeRevert Selective Rollback Receipt   [or "... Receipt (Dry-Run)"]
//
//   ## Summary
//
//   - **Rollback ID:** `<rb_id>`
//   - ...
//
//   ## Selectors
//   ## Resolved Change Groups
//   ## Results
//   ## First Verification          [apply only]
//   ## Project Verification        [apply only]
//   ## Post-Command Integrity      [apply only]
//   ## Out of Scope
//
//   ---
//
//   Generated by VibeRevert v<version>

import type {
  ApplyPathResult,
  DryRunPathResult,
  FailureSummary,
  FirstVerification,
  PostCommandIntegrity,
  ProjectVerification,
  RollbackSelectors,
  SelectiveRollbackReceipt,
  VerifyCommandRecord,
} from "@viberevert/session-format";

import { bracketToken, inlineCode, inlineMarkdown, schemaToken } from "./markdown-escape.js";
import type { SelectiveReceiptRenderInput } from "./selective-receipt-types.js";

const bullet = (label: string, value: string): string => `- **${label}:** ${value}`;

const failureBullets = (failure: FailureSummary): readonly string[] => [
  bullet("Error code", `**${bracketToken(failure.error_code)}**`),
  bullet("Message", inlineMarkdown(failure.message)),
];

function selectorBullets(selectors: RollbackSelectors): readonly string[] {
  const lines: string[] = [];
  for (const value of selectors.only ?? []) lines.push(`- \`--only\` ${inlineCode(value)}`);
  for (const value of selectors.except ?? []) lines.push(`- \`--except\` ${inlineCode(value)}`);
  for (const value of selectors.finding ?? []) lines.push(`- \`--finding\` ${inlineCode(value)}`);
  if (selectors.risk !== undefined) {
    lines.push(`- \`--risk\` ${schemaToken(selectors.risk)}`);
  }
  return lines.length === 0 ? ["(none)"] : lines;
}

function resultBullets(
  results: readonly (DryRunPathResult | ApplyPathResult)[],
): readonly string[] {
  if (results.length === 0) return ["(none)"];
  const lines: string[] = [];
  for (const result of results) {
    lines.push(`- **${bracketToken(result.outcome)}** ${inlineCode(result.path)}`);
    lines.push(`  - Change group: ${inlineCode(result.change_group_id)}`);
    if (result.reason !== undefined) {
      lines.push(`  - Reason: ${inlineMarkdown(result.reason)}`);
    }
  }
  return lines;
}

function firstVerificationBullets(verification: FirstVerification): readonly string[] {
  switch (verification.state) {
    case "completed": {
      const a = verification.assessment;
      return [
        bullet("State", schemaToken("completed")),
        bullet("Selected verified", String(a.selected_verified)),
        bullet("Unselected checked", String(a.unselected_checked_count)),
        bullet("HEAD unchanged", String(a.head_unchanged)),
        ...(a.unselected_violations.length === 0
          ? [bullet("Unselected violations", "(none)")]
          : [
              `- **Unselected violations (${a.unselected_violations.length}):**`,
              ...a.unselected_violations.map((path) => `  - ${inlineCode(path)}`),
            ]),
      ];
    }
    case "failed":
      return [
        bullet("State", schemaToken("failed")),
        ...failureBullets(verification.failure),
        "",
        "The verification started and threw, so no per-path facts exist.",
      ];
    case "not_run":
      return [
        bullet("State", schemaToken("not_run")),
        bullet("Reason", schemaToken(verification.reason)),
        "",
        "No gate result exists, so the transplant was never verified. The mutation may still have been authorized; treat every result as indeterminate and recover from the pre-rollback checkpoint.",
      ];
    default: {
      const unhandled: never = verification;
      return unhandled;
    }
  }
}

function commandBullets(record: VerifyCommandRecord): readonly string[] {
  const argv = inlineCode([record.command, ...record.args].join(" "));
  const result = record.result;
  switch (result.outcome) {
    case "exited":
      return [
        `- **${bracketToken(result.exit_code === 0 ? "passed" : "failed")}** ${argv}`,
        `  - Exit code: ${result.exit_code}`,
      ];
    case "signalled":
      return [
        `- **${bracketToken("signalled")}** ${argv}`,
        `  - Signal: ${inlineMarkdown(result.signal)}`,
      ];
    case "unresolved":
      return [
        `- **${bracketToken("unresolved")}** ${argv}`,
        "  - The command name resolved to nothing on PATH.",
      ];
    case "unsupported_target":
      return [
        `- **${bracketToken("unsupported_target")}** ${argv}`,
        `  - Resolved to: ${inlineCode(result.resolved_target)}`,
        `  - Kind: ${schemaToken(result.kind)}`,
      ];
    case "not_run":
      return [
        `- **${bracketToken("not_run")}** ${argv}`,
        `  - Reason: ${schemaToken(result.reason)}`,
      ];
    default: {
      const unhandled: never = result;
      return unhandled;
    }
  }
}

function projectVerificationBullets(verification: ProjectVerification): readonly string[] {
  switch (verification.state) {
    case "not_configured":
      return [
        bullet("State", schemaToken("not_configured")),
        "",
        "The session configured no verification commands.",
      ];
    case "skipped":
      return [
        bullet("State", schemaToken("skipped")),
        bullet("Reason", schemaToken(verification.reason)),
      ];
    case "completed":
      return verification.commands.length === 0
        ? [bullet("State", schemaToken("completed")), "", "(none)"]
        : [
            bullet("State", schemaToken("completed")),
            "",
            ...verification.commands.flatMap((record) => commandBullets(record)),
          ];
    case "runner_failed":
      return [
        bullet("State", schemaToken("runner_failed")),
        ...failureBullets(verification.failure),
        "",
        "The runner itself faulted. This is not a command reporting failure.",
      ];
    default: {
      const unhandled: never = verification;
      return unhandled;
    }
  }
}

function postCommandIntegrityBullets(integrity: PostCommandIntegrity): readonly string[] {
  switch (integrity.state) {
    case "not_run":
      return [
        bullet("State", schemaToken("not_run")),
        bullet("Reason", schemaToken(integrity.reason)),
      ];
    case "clean":
      return [
        bullet("State", schemaToken("clean")),
        "",
        "The project is byte-for-byte what the transplant left behind.",
      ];
    case "project_mutated": {
      const group = (title: string, paths: readonly string[]): readonly string[] =>
        paths.length === 0
          ? []
          : [`- **${title} (${paths.length}):**`, ...paths.map((p) => `  - ${inlineCode(p)}`)];
      return [
        bullet("State", schemaToken("project_mutated")),
        bullet("HEAD moved", String(integrity.head_moved)),
        ...group("Added", integrity.added_paths),
        ...group("Removed", integrity.removed_paths),
        ...group("Changed", integrity.changed_paths),
        ...group("Topology changed roots", integrity.topology_changed_roots),
        "",
        "A verification command changed the project after the transplant.",
      ];
    }
    case "basis_changed":
      return [
        bullet("State", schemaToken("basis_changed")),
        "",
        "The ignore rules moved during the run, so the two observations cover different domains and cannot be compared.",
      ];
    case "observation_failed":
      return [
        bullet("State", schemaToken("observation_failed")),
        bullet("Side", schemaToken(integrity.side)),
        ...failureBullets(integrity.failure),
      ];
    case "observation_torn":
      return [
        bullet("State", schemaToken("observation_torn")),
        bullet("Side", schemaToken(integrity.side)),
        bullet("Basis moved", String(integrity.basis_moved)),
        bullet("HEAD moved", String(integrity.head_moved)),
        bullet("Domain", schemaToken(integrity.domain_status)),
        "",
        "The observation changed while it was being taken, so it describes no single moment and cannot support a comparison.",
      ];
    case "classification_failed":
      return [
        bullet("State", schemaToken("classification_failed")),
        ...failureBullets(integrity.failure),
        "",
        "Both observations were coherent; comparing them faulted.",
      ];
    default: {
      const unhandled: never = integrity;
      return unhandled;
    }
  }
}

function summaryBullets(file: SelectiveRollbackReceipt): readonly string[] {
  const shared = [
    bullet("Rollback ID", inlineCode(file.rollback_id)),
    bullet("Session ID", inlineCode(file.session_id)),
    bullet("Checkpoint ID", inlineCode(file.checkpoint_id)),
    bullet("Contribution", inlineCode(file.contribution_sha256)),
    bullet("Mode", schemaToken(file.mode)),
  ];
  // Header fields render as PLAIN schema tokens, matching the legacy receipt.
  // The bracketed uppercase form is reserved for per-entry outcomes -- a path
  // result, a command result, an error code -- so a reader can tell at a
  // glance whether a token describes the whole operation or one row of it.
  return file.mode === "apply"
    ? [
        ...shared,
        bullet("Pre-rollback checkpoint", inlineCode(file.pre_rollback_checkpoint_id)),
        bullet("Outcome", schemaToken(file.outcome)),
        bullet("Written at", inlineCode(file.written_at)),
      ]
    : [
        ...shared,
        bullet("Eligibility", schemaToken(file.eligibility)),
        bullet("Written at", inlineCode(file.written_at)),
      ];
}

/**
 * Render a selective rollback receipt as CommonMark.
 *
 * Pure and synchronous: no I/O, no clock, no randomness, no stream writes.
 */
export function renderSelectiveReceiptMarkdown(input: SelectiveReceiptRenderInput): string {
  const file = input.file;

  const lines: string[] = [
    file.mode === "dry_run"
      ? "# VibeRevert Selective Rollback Receipt (Dry-Run)"
      : "# VibeRevert Selective Rollback Receipt",
    "",
    "## Summary",
    "",
    ...summaryBullets(file),
    "",
    "## Selectors",
    "",
    ...selectorBullets(file.selectors),
    "",
    `## Resolved Change Groups (${file.resolved_change_group_ids.length})`,
    "",
    ...(file.resolved_change_group_ids.length === 0
      ? ["(none)"]
      : file.resolved_change_group_ids.map((id) => `- ${inlineCode(id)}`)),
    "",
    `## Results (${file.results.length})`,
    "",
    ...resultBullets(file.results),
    "",
  ];

  if (file.mode === "apply") {
    lines.push(
      "## First Verification",
      "",
      ...firstVerificationBullets(file.first_verification),
      "",
      "## Project Verification",
      "",
      ...projectVerificationBullets(file.project_verification),
      "",
      "## Post-Command Integrity",
      "",
      ...postCommandIntegrityBullets(file.post_command_integrity),
      "",
    );
  }

  lines.push(
    "## Out of Scope",
    "",
    inlineMarkdown(file.out_of_scope_notice),
    "",
    "---",
    "",
    `Generated by VibeRevert v${inlineMarkdown(input.productVersion)}`,
  );

  return `${lines.join("\n")}\n`;
}
