// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// renderTerminal: ANSI-free plain-text rendering of a ReportFile
// for human-facing CLI output.
//
// =============================================================================
// CONTRACT (D45 + D55 + D54)
// =============================================================================
//
// Output is:
//   - PURE STRING — caller (CLI) writes to stdout; reporters never
//     write to terminal streams per D29.
//   - ANSI-FREE — no color codes, no escape sequences. M C ships
//     without color per D55; the CLI may wrap with a color helper
//     in a later milestone. Plain ASCII keeps the output portable
//     and golden-fixture-friendly (byte-stable across platforms
//     and locales).
//   - FIXED 80-COLUMN LAYOUT — no terminal-width probing per the
//     M B D18 precedent. Section dividers are 80-char ASCII rules.
//     Lines that naturally exceed 80 chars (long file paths, long
//     recommendation text) are NOT truncated; the renderer trusts
//     the terminal to wrap them visually.
//   - NEWLINE-TERMINATED — the final character is always '\n', so
//     the CLI can write the string directly without appending.
//
// =============================================================================
// LAYOUT (LOCKED — drives golden fixtures from Step 10)
// =============================================================================
//
// This layout closes the M C plan's last remaining Open Question
// (the "exact terminal column widths" item). Any future layout
// change requires a deliberate `pnpm regen-goldens` run + commit.
//
//   ================================================================================
//   VibeRevert Report
//   ================================================================================
//
//   Report ID:    <id>
//   Kind:         <kind>
//   Since:        <ref> (kind: <since_kind>)
//   Resolved SHA: <sha>
//   Written at:   <iso>
//   Staged-only:  true                              [only when present]
//   Task:         <task>                            [only when present]
//   Frameworks:   <comma-separated, or "(none)">
//
//   Risk Level:   <UPPERCASE>
//   Summary:      <summary string>                  [only when present]
//
//   --------------------------------------------------------------------------------
//   Findings (<N>)
//   --------------------------------------------------------------------------------
//
//   [<LEVEL>] <category>: <title>                   [§14 convention]
//     Message: <message>
//     File: <path>[:<line>]                         [single-evidence form]
//     Command: <command>                            [when evidence.command present]
//     Detail: <detail>
//     Recommendation: <reco>                        [when present]
//
//   [<LEVEL>] <category>: <title>
//     Message: <message>
//     Evidence:                                     [multi-evidence form]
//       - <subject> (<detail>)
//       - <subject> (<detail>)
//     Recommendation: <reco>
//
//   --------------------------------------------------------------------------------
//   Changed Files (<N>)
//   --------------------------------------------------------------------------------
//
//   <S>  <path>  [<tags>]  <LEVEL>
//   R    <new-path>  [<tags>]  <LEVEL>  (was: <previous-path>)
//
// Status codes (S): A = added, M = modified, D = deleted,
// R = renamed, T = type_changed.
//
// Risk tags are joined with ", " inside the square brackets; empty
// tags array renders as "[]". Empty sections (zero findings, zero
// changed files) render the placeholder "(none)" rather than
// vanishing — keeps the layout shape predictable for human
// scanning and byte-stable for golden fixtures.
//
// NO version footer in terminal output. Version-stamping is
// markdown-only per the D45 locked footer ("Generated by
// VibeRevert v<version>") and the types.ts narrowed productVersion
// docs — adding it to terminal would broaden the locked surface
// without a justifying use case. `input.productVersion` is accepted
// on the RenderInput shape for API uniformity across renderers but
// is intentionally NOT consumed by renderTerminal.

import type { ChangedFile, CheckResult, Evidence, ReportFile } from "@viberevert/session-format";

import { applyThreshold } from "./threshold.js";
import type { RenderInput } from "./types.js";

// =============================================================================
// Locked layout constants
// =============================================================================

const TERMINAL_WIDTH = 80;
const RULE_DOUBLE = "=".repeat(TERMINAL_WIDTH);
const RULE_SINGLE = "-".repeat(TERMINAL_WIDTH);

// Header label column width. Chosen so the widest label
// ("Resolved SHA:" = 13 chars) aligns with the rest, plus one
// trailing space → 14. If a longer label is ever added, bump this
// constant AND regenerate goldens.
const HEADER_LABEL_WIDTH = 14;

// 1-char status codes mirror git porcelain conventions.
const STATUS_CODES: Readonly<Record<string, string>> = {
  added: "A",
  modified: "M",
  deleted: "D",
  renamed: "R",
  type_changed: "T",
};

// =============================================================================
// Tiny formatting helpers
// =============================================================================

/** Pad a string to `width` columns with trailing spaces. */
function padRight(text: string, width: number): string {
  if (text.length >= width) return text;
  return text + " ".repeat(width - text.length);
}

/** Map a ChangedFileStatus value to a 1-char status code. */
function statusCode(status: string): string {
  return STATUS_CODES[status] ?? "?";
}

/** Format a labeled header line: "Label:        value". */
function headerLine(label: string, value: string): string {
  return padRight(`${label}:`, HEADER_LABEL_WIDTH) + value;
}

/** Format the level token in brackets: "[CRITICAL]". */
function levelToken(level: string): string {
  return `[${level.toUpperCase()}]`;
}

/**
 * Format an evidence entry as the inline-form string used in the
 * multi-evidence list. Builds a "subject (detail)" form when a
 * subject (file:line, file, or command) is available; otherwise
 * just the detail alone.
 */
function evidenceLine(ev: Evidence): string {
  let subject = "";
  if (ev.file !== undefined) {
    subject = ev.line !== undefined ? `${ev.file}:${ev.line}` : ev.file;
  } else if (ev.command !== undefined) {
    subject = `command: ${ev.command}`;
  }
  return subject === "" ? ev.detail : `${subject} (${ev.detail})`;
}

// =============================================================================
// Section builders
// =============================================================================

function buildHeader(file: ReportFile): string[] {
  const lines: string[] = [];
  lines.push(RULE_DOUBLE);
  lines.push("VibeRevert Report");
  lines.push(RULE_DOUBLE);
  lines.push("");
  lines.push(headerLine("Report ID", file.report_id));
  lines.push(headerLine("Kind", file.kind));
  lines.push(headerLine("Since", `${file.since_ref} (kind: ${file.since_kind})`));
  lines.push(headerLine("Resolved SHA", file.since_resolved_sha));
  lines.push(headerLine("Written at", file.written_at));
  if (file.staged_only === true) {
    lines.push(headerLine("Staged-only", "true"));
  }
  if (file.report.task !== undefined) {
    lines.push(headerLine("Task", file.report.task));
  }
  const frameworks =
    file.report.detected_frameworks.length === 0
      ? "(none)"
      : file.report.detected_frameworks.join(", ");
  lines.push(headerLine("Frameworks", frameworks));
  lines.push("");
  lines.push(headerLine("Risk Level", file.report.risk_level.toUpperCase()));
  if (file.report.summary !== undefined) {
    lines.push(headerLine("Summary", file.report.summary));
  }
  return lines;
}

function buildFinding(result: CheckResult): string[] {
  const lines: string[] = [];
  lines.push(`${levelToken(result.level)} ${result.category}: ${result.title}`);
  lines.push(`  Message: ${result.message}`);

  if (result.evidence.length === 1) {
    const ev = result.evidence[0];
    if (ev !== undefined) {
      if (ev.file !== undefined) {
        const path = ev.line !== undefined ? `${ev.file}:${ev.line}` : ev.file;
        lines.push(`  File: ${path}`);
      }
      if (ev.command !== undefined) {
        lines.push(`  Command: ${ev.command}`);
      }
      lines.push(`  Detail: ${ev.detail}`);
    }
  } else {
    lines.push("  Evidence:");
    for (const ev of result.evidence) {
      lines.push(`    - ${evidenceLine(ev)}`);
    }
  }

  if (result.recommendation !== undefined && result.recommendation.length > 0) {
    lines.push(`  Recommendation: ${result.recommendation}`);
  }

  return lines;
}

function buildFindingsSection(results: readonly CheckResult[]): string[] {
  const lines: string[] = [];
  lines.push(RULE_SINGLE);
  lines.push(`Findings (${results.length})`);
  lines.push(RULE_SINGLE);
  lines.push("");

  if (results.length === 0) {
    lines.push("(none)");
    return lines;
  }

  for (const [i, finding] of results.entries()) {
    for (const line of buildFinding(finding)) {
      lines.push(line);
    }
    if (i < results.length - 1) {
      lines.push("");
    }
  }
  return lines;
}

function buildChangedFile(cf: ChangedFile): string {
  const tags = cf.risk_tags.length === 0 ? "[]" : `[${cf.risk_tags.join(", ")}]`;
  const level = cf.risk_level.toUpperCase();
  const base = `${statusCode(cf.status)}  ${cf.path}  ${tags}  ${level}`;
  if (cf.status === "renamed" && cf.previous_path !== undefined) {
    return `${base}  (was: ${cf.previous_path})`;
  }
  return base;
}

function buildChangedFilesSection(changedFiles: readonly ChangedFile[]): string[] {
  const lines: string[] = [];
  lines.push(RULE_SINGLE);
  lines.push(`Changed Files (${changedFiles.length})`);
  lines.push(RULE_SINGLE);
  lines.push("");
  if (changedFiles.length === 0) {
    lines.push("(none)");
    return lines;
  }
  for (const cf of changedFiles) {
    lines.push(buildChangedFile(cf));
  }
  return lines;
}

// =============================================================================
// renderTerminal
// =============================================================================

/**
 * Render a ReportFile as ANSI-free plain text suitable for CLI
 * terminal output. Applies `input.threshold` per D38 before
 * formatting. The output is newline-terminated.
 *
 * `input.productVersion` is intentionally NOT consumed — terminal
 * output has no locked version footer (markdown owns the
 * "Generated by VibeRevert v<version>" line per D45). The field
 * remains on RenderInput for API uniformity across renderers; the
 * render() dispatcher passes the same shape to all.
 *
 * Pure synchronous: no I/O, no Date.now(), no Math.random().
 *
 * The caller (CLI) is responsible for writing the returned string
 * to stdout per the D29 boundary — reporters never write to
 * terminal streams.
 */
export function renderTerminal(input: RenderInput): string {
  const file = applyThreshold(input.file, input.threshold);

  const sections: string[][] = [
    buildHeader(file),
    [""],
    buildFindingsSection(file.report.results),
    [""],
    buildChangedFilesSection(file.report.changed_files),
  ];

  return `${sections.flat().join("\n")}\n`;
}
