// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// H11.1 launcher protect guard — the two currently-WORKING VibeRevert launch
// forms must not be changed as collateral damage while fixing the separate
// Cursor launcher context.
//
// Context (ADR 0005 Decision 5): on Windows the Claude Code MCP client and the
// git `sh` that runs the generated pre-commit hook already launch the bare
// `viberevert` command successfully. Cursor is a SEPARATE, client-owned
// launcher context that cannot. Its fix (H11.3) — and the internal-spawn fix
// (H11.2) — must NOT be copied onto the Claude MCP config or the direct hook
// merely for symmetry.
//
// This guard pins those two working forms as the single cross-cutting H11
// regression anchor. Its overlap with claude.test.ts / direct-hook.test.ts is
// intentional: the per-adapter tests prove each adapter emits its expected
// artifact; this guard proves the bare launch form is preserved against the
// Cursor/internal-spawn fixes. It validates generated bytes only, so it runs on
// every host (NOT Windows-gated).

import { randomUUID } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { claudeAdapter } from "../../src/adapters/claude.js";
import { directHookAdapter } from "../../src/adapters/direct-hook.js";
import type { AdapterContext } from "../../src/types.js";

// A minimal AdapterContext with a unique, nonexistent repoRoot. The Adapter
// contract types plan(ctx); Claude's current implementation does not use it
// (declarative), and direct-hook's reads it and, finding no hook (ENOENT),
// yields the write-new plan whose content we pin.
function makeCtx(): AdapterContext {
  return {
    repoRoot: join(tmpdir(), `vr-launcher-protect-${randomUUID()}`),
    now: new Date("2026-06-27T12:00:00.000Z"),
    cliVersion: "0.7.1-beta.0",
    intent: "explicit",
    options: { forceReinstall: false, migrateFromHookInstall: false, forceUninstall: false },
  };
}

describe("H11 Windows launcher protect guard (ADR 0005 Decision 5)", () => {
  it("Claude MCP config keeps the bare `viberevert` stdio launch form", async () => {
    const plan = await claudeAdapter.plan(makeCtx());
    if (plan.status !== "applicable") throw new Error("expected applicable plan");
    const op = plan.ops[0];
    expect(op).toBeDefined();
    if (op === undefined) return;
    if (op.kind !== "json-key-merge") throw new Error("expected json-key-merge op");

    // Destination pinned so the launch form cannot be satisfied in the wrong
    // configuration location.
    expect(op.target.pathRelative).toBe(".mcp.json");
    expect(op.target.pathTemplate).toBe("{repo}/.mcp.json");
    expect(op.keyPath).toEqual(["mcpServers", "viberevert"]);

    // Load-bearing launcher shape: bare command, not a cmd.exe / absolute wrapper.
    expect(op.value).toMatchObject({
      type: "stdio",
      command: "viberevert",
      args: ["mcp", "serve"],
    });
  });

  it("direct pre-commit hook invokes the bare `viberevert` command", async () => {
    const plan = await directHookAdapter.plan(makeCtx());
    if (plan.status !== "applicable") throw new Error("expected applicable plan");
    const op = plan.ops[0];
    expect(op).toBeDefined();
    if (op === undefined) return;
    if (op.kind !== "write-new") throw new Error("expected write-new op");

    // Select non-comment command lines, trimmed so the assertion pins the shell
    // command rather than incidental indentation (line endings normalized).
    const commandLines = op.content
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line !== "" && !line.startsWith("#"));

    // The executable invocation line is exactly the bare command — not wrapped.
    expect(commandLines).toContain("viberevert check --staged");

    // Negative guards against the collateral transformations being prevented.
    expect(op.content).not.toMatch(/\bcmd(?:\.exe)?\b/i);
    expect(op.content).not.toMatch(/\bcomspec\b/i);
  });
});
