// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Zod schemas for the durable .viberevert/integrations.json file
// per D101.C + D101.D + D101.D' + D101.O.
//
// This module defines the SHAPE of every value persisted in the
// integrations store. Every schema is `.strict()` so unknown fields
// fail validation rather than silently round-trip. The schema is the
// boundary between in-memory engine state and on-disk bytes; once
// data passes parse, downstream code can treat its types as
// validated facts.
//
// PathSpec boundary (rule 14: no global writes; D101.D POSIX-only):
//   - non-empty string
//   - bounded length (.max(512))
//   - no control characters (rejects the full C0 range 0x00-0x1F
//     plus DEL 0x7F)
//   - no backslash (POSIX forward slashes only -- catches UNC
//     "\\server\..." too)
//   - no leading slash (must be relative)
//   - no Windows drive letter ("C:/...", "d:\\...")
//   - no colon anywhere (avoids Windows alternate data streams
//     "file:stream" + embedded drive-letter ambiguity "dir/C:/x")
//   - no leading "~" (no home expansion)
//   - no empty segments ("foo//bar"), no "." segments, no ".."
//     segments (no traversal)
// path-resolve.ts and preflight-target.ts trust these properties at
// runtime; this schema is the enforcement boundary.
//
// pathTemplate is descriptive/provenance only; pathRelative is the
// AUTHORITY for resolving the actual on-disk target. pathTemplate is
// still bounded + control-char-free since it appears in durable
// audit text.
//
// All audit-facing strings (adapterName, version strings, blockId,
// pathTemplate, metadata keys/values) reject control characters and
// have conservative max-length caps. A 5 MB blockId or a version
// string with embedded NUL should never parse.
//
// Control-character detection uses a `hasControlChar` helper with
// charCodeAt + numeric comparisons (NOT a regex literal containing
// control-char escapes). This keeps the source file ASCII-only and
// readable; literal `\uXXXX` escapes in regex sources are fragile
// across tool pipelines (grep/diff/editors may treat them as binary
// content after JSON round-tripping).
//
// IntegrationFileEditRecord per-kind discipline (D101.C + D101.D'):
// a superRefine enforces in BOTH directions
//   - the required SHA + companion fields for the record's kind ARE
//     non-null;
//   - the SHAs + companion fields for OTHER kinds ARE null.
// This catches malformed records that include leftover fields from
// a different op kind. backup is required for backup-and-write and
// MUST be null for all other kinds -- otherwise a malformed record
// could parse but be impossible to uninstall safely.
//
// jsonKeyPath uses JsonKeySegmentSchema to reject prototype-pollution
// keys (__proto__, constructor, prototype), control characters, and
// empty segments. jsonKeyPath array must itself be non-empty (an
// empty path is meaningless).
//
// ops array must be non-empty (a record with zero ops is meaningless
// and dangerous for uninstall accounting).
//
// records map: z.partialRecord(RecordKeySchema, ...) -- sparse, not
// every RecordKey enum value must be present. Matches plan invariant
// A51. A root superRefine then asserts each map-key matches its
// record's own recordKey field (otherwise records.cursor.recordKey
// could say "claude" and we'd be wrong about who installed what).
//
// meta is bounded: keys (.max(128) + no-ctrl), values (.max(2048) +
// no-ctrl), AND total entries .max(64). A bounded record key/value
// schema alone wouldn't prevent thousands of entries from inflating
// the durable file.
//
// history is .max(1000) -- does not solve pruning, but prevents
// absurd durable files from parsing as valid.
//
// schemaVersion / createdByVersion / updatedByVersion are validated
// shape only; they are NEVER trust input for security decisions.
// Version metadata documents the writer; it does not authorize
// behavior.
//
// Timestamps use z.iso.datetime() plus an explicit "Z" suffix
// refinement. This locks the durable contract to UTC strings
// generated by `new Date().toISOString()`. The explicit refinement
// is belt-and-braces: even if Zod's default datetime options change
// in a future release, our schema still requires `Z`.

import { z } from "zod";

import { RECORD_KEYS } from "./engine-types.js";

const SHA256_HEX_REGEX = /^[0-9a-f]{64}$/;

// Detect any control character: C0 range (0x00-0x1F) or DEL (0x7F).
// Implemented as charCodeAt comparison (NOT a regex literal with
// \uXXXX escapes) so the source file stays ASCII-only and readable.
function hasControlChar(s: string): boolean {
  for (let i = 0; i < s.length; i++) {
    const code = s.charCodeAt(i);
    if (code <= 0x1f || code === 0x7f) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Helper: bounded length + no control chars. Returned schema can be
// used directly as an object-property value schema and can be chained
// with .nullable().
// ---------------------------------------------------------------------------

function boundedNoControlString(args: { min: number; max: number; label: string }) {
  return z
    .string()
    .min(args.min)
    .max(args.max)
    .refine((s) => !hasControlChar(s), {
      message: `${args.label} must not contain control characters`,
    });
}

// Reusable audit-facing string schemas.
const VersionStringSchema = boundedNoControlString({
  min: 1,
  max: 128,
  label: "version strings",
});
const AdapterNameSchema = boundedNoControlString({
  min: 1,
  max: 128,
  label: "adapterName",
});
const BlockIdSchema = boundedNoControlString({
  min: 1,
  max: 256,
  label: "blockId",
});
const PathTemplateSchema = boundedNoControlString({
  min: 1,
  max: 512,
  label: "pathTemplate",
});

// UTC-only ISO datetime. z.iso.datetime() handles the ISO shape;
// the explicit endsWith("Z") refinement locks the UTC contract
// regardless of Zod's default option behavior in future versions.
const UtcIsoDateTimeSchema = z.iso.datetime().refine((s) => s.endsWith("Z"), {
  message: "datetime must be UTC and end with Z",
});

// ---------------------------------------------------------------------------
// RecordKey -- single source of literals via engine-types' RECORD_KEYS.
// ---------------------------------------------------------------------------

export const RecordKeySchema = z.enum(RECORD_KEYS);

// ---------------------------------------------------------------------------
// PathSpec -- boundary refinements per rule 14 + D101.D. Refinement
// order is chosen for clearest first-failure diagnostics: backslash
// first (catches most Windows mistakes), then leading slash, then
// drive letter (specific Windows form), then colon (Windows ADS +
// general drive-letter ambiguity), then `~`, then segment-level
// emptiness/traversal.
// ---------------------------------------------------------------------------

const PathRelativeString = z
  .string()
  .min(1, { message: "pathRelative must be non-empty" })
  .max(512, { message: "pathRelative must be <= 512 characters" })
  .refine((s) => !hasControlChar(s), {
    message: "pathRelative must not contain control characters",
  })
  .refine((s) => !s.includes("\\"), {
    message: "pathRelative must use POSIX forward slashes; no backslashes allowed",
  })
  .refine((s) => !s.startsWith("/"), {
    message: "pathRelative must be repo-relative; no leading slash",
  })
  .refine((s) => !/^[a-zA-Z]:/.test(s), {
    message: "pathRelative must not be a Windows absolute path (drive letter)",
  })
  .refine((s) => !s.includes(":"), {
    message:
      "pathRelative must not contain ':' (avoids Windows alternate data streams and embedded drive-letter ambiguity)",
  })
  .refine((s) => !s.startsWith("~"), {
    message: "pathRelative must not start with ~ (no home expansion)",
  })
  .refine(
    (s) => {
      const segments = s.split("/");
      return segments.every((seg) => seg.length > 0 && seg !== "." && seg !== "..");
    },
    {
      message: "pathRelative must not contain empty segments, '.', or '..' (no traversal)",
    },
  );

export const PathSpecSchema = z
  .object({
    scope: z.literal("repo"),
    pathTemplate: PathTemplateSchema,
    pathRelative: PathRelativeString,
  })
  .strict();

// ---------------------------------------------------------------------------
// JSON-key segment -- proto-pollution + control-char rejection.
// ---------------------------------------------------------------------------

const JsonKeySegmentSchema = z
  .string()
  .min(1)
  .max(256)
  .refine((s) => !hasControlChar(s), {
    message: "jsonKeyPath segments must not contain control characters",
  })
  .refine((s) => s !== "__proto__" && s !== "constructor" && s !== "prototype", {
    message:
      "jsonKeyPath must not contain prototype-pollution keys (__proto__, constructor, prototype)",
  });

// ---------------------------------------------------------------------------
// IntegrationFileEditRecord -- per-kind SHA + companion-field discipline.
// ---------------------------------------------------------------------------

const FILE_EDIT_OP_KINDS = [
  "write-new",
  "sentinel-block-insert",
  "sentinel-block-replace",
  "backup-and-write",
  "json-key-merge",
] as const;

export const IntegrationFileEditRecordSchema = z
  .object({
    kind: z.enum(FILE_EDIT_OP_KINDS),
    target: PathSpecSchema,
    backup: PathSpecSchema.nullable(),
    managedBlockSha256: z.string().regex(SHA256_HEX_REGEX).nullable(),
    managedValueSha256: z.string().regex(SHA256_HEX_REGEX).nullable(),
    fullFileSha256AfterWrite: z.string().regex(SHA256_HEX_REGEX).nullable(),
    blockId: BlockIdSchema.nullable(),
    jsonKeyPath: z.array(JsonKeySegmentSchema).min(1).nullable(),
    // mode means the POSIX mode the engine SETS the file to AFTER
    // install (used for hook scripts on POSIX). It is NOT "the mode
    // the file had before install" -- pre-install permissions are
    // captured via the backup file (for backup-and-write) or
    // implicit (for write-new on a fresh path).
    mode: z.number().int().min(0).max(0o777).nullable(),
  })
  .strict()
  .superRefine((rec, ctx) => {
    // Exactly one SHA field non-null.
    const shaCount = [
      rec.managedBlockSha256,
      rec.managedValueSha256,
      rec.fullFileSha256AfterWrite,
    ].filter((s) => s !== null).length;
    if (shaCount !== 1) {
      ctx.addIssue({
        code: "custom",
        message: `Exactly one SHA field must be non-null; got ${shaCount}.`,
      });
    }

    // Per-kind: required fields non-null + inapplicable fields null.
    if (rec.kind === "sentinel-block-insert" || rec.kind === "sentinel-block-replace") {
      if (rec.managedBlockSha256 === null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires managedBlockSha256.`,
        });
      }
      if (rec.blockId === null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires blockId.`,
        });
      }
      if (rec.jsonKeyPath !== null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires jsonKeyPath to be null.`,
        });
      }
      if (rec.mode !== null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires mode to be null.`,
        });
      }
    } else if (rec.kind === "json-key-merge") {
      if (rec.managedValueSha256 === null) {
        ctx.addIssue({
          code: "custom",
          message: "json-key-merge requires managedValueSha256.",
        });
      }
      if (rec.jsonKeyPath === null) {
        ctx.addIssue({
          code: "custom",
          message: "json-key-merge requires jsonKeyPath.",
        });
      }
      if (rec.blockId !== null) {
        ctx.addIssue({
          code: "custom",
          message: "json-key-merge requires blockId to be null.",
        });
      }
      if (rec.mode !== null) {
        ctx.addIssue({
          code: "custom",
          message: "json-key-merge requires mode to be null.",
        });
      }
    } else {
      // write-new or backup-and-write
      if (rec.fullFileSha256AfterWrite === null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires fullFileSha256AfterWrite.`,
        });
      }
      if (rec.blockId !== null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires blockId to be null.`,
        });
      }
      if (rec.jsonKeyPath !== null) {
        ctx.addIssue({
          code: "custom",
          message: `${rec.kind} requires jsonKeyPath to be null.`,
        });
      }
      // mode may be set for write-new / backup-and-write (engine uses
      // it for chmod on POSIX hook installers); no null requirement.
    }

    // backup discipline: backup-and-write requires a backup record;
    // all other kinds require backup to be null. Without this, a
    // malformed backup-and-write could parse with backup === null
    // and be impossible to uninstall safely.
    if (rec.kind === "backup-and-write") {
      if (rec.backup === null) {
        ctx.addIssue({
          code: "custom",
          message: "backup-and-write requires backup.",
        });
      }
    } else if (rec.backup !== null) {
      ctx.addIssue({
        code: "custom",
        message: `${rec.kind} requires backup to be null.`,
      });
    }
  });

// ---------------------------------------------------------------------------
// Metadata -- bounded keys + bounded values + bounded entry count.
// ---------------------------------------------------------------------------

const MetadataKeySchema = boundedNoControlString({
  min: 1,
  max: 128,
  label: "metadata keys",
});
const MetadataValueSchema = boundedNoControlString({
  min: 0,
  max: 2048,
  label: "metadata values",
});
const MetadataSchema = z
  .record(MetadataKeySchema, MetadataValueSchema)
  .refine((m) => Object.keys(m).length <= 64, {
    message: "metadata must contain at most 64 entries",
  });

// ---------------------------------------------------------------------------
// IntegrationRecord -- one record per installed adapter.
// ---------------------------------------------------------------------------

export const IntegrationRecordSchema = z
  .object({
    recordKey: RecordKeySchema,
    adapterName: AdapterNameSchema,
    installedAt: UtcIsoDateTimeSchema,
    installedByVersion: VersionStringSchema,
    ops: z.array(IntegrationFileEditRecordSchema).min(1),
    meta: MetadataSchema,
  })
  .strict();

// ---------------------------------------------------------------------------
// IntegrationsFile -- the root .viberevert/integrations.json shape.
// ---------------------------------------------------------------------------

const HistoryEntrySchema = z
  .object({
    timestamp: UtcIsoDateTimeSchema,
    action: z.enum(["install", "uninstall", "migrate", "adopt"]),
    recordKey: RecordKeySchema,
    cliVersion: VersionStringSchema,
  })
  .strict();

export const IntegrationsFileSchema = z
  .object({
    schemaVersion: z.literal(1),
    createdByVersion: VersionStringSchema,
    updatedByVersion: VersionStringSchema,
    records: z.partialRecord(RecordKeySchema, IntegrationRecordSchema),
    history: z.array(HistoryEntrySchema).max(1000),
  })
  .strict()
  .superRefine((file, ctx) => {
    // Map-key consistency: records.<key>.recordKey must equal <key>.
    // Without this, records.cursor.recordKey could say "claude" and
    // the store would be durably wrong about which adapter installed
    // what.
    for (const [mapKey, record] of Object.entries(file.records)) {
      if (record !== undefined && record.recordKey !== mapKey) {
        ctx.addIssue({
          code: "custom",
          path: ["records", mapKey, "recordKey"],
          message: `recordKey must match records map key "${mapKey}".`,
        });
      }
    }
  });

// ---------------------------------------------------------------------------
// Exported types -- derived via z.infer; RecordKey re-exported from
// engine-types so RECORD_KEYS stays the single source.
// ---------------------------------------------------------------------------

export type PathSpec = z.infer<typeof PathSpecSchema>;
export type IntegrationFileEditRecord = z.infer<typeof IntegrationFileEditRecordSchema>;
export type IntegrationRecord = z.infer<typeof IntegrationRecordSchema>;
export type IntegrationsFile = z.infer<typeof IntegrationsFileSchema>;
