// SPDX-FileCopyrightText: 2026 Fabio Marcello Salvadori
// SPDX-License-Identifier: Apache-2.0

/**
 * GitHub Action workflow template generator for @viberevert/adapters.
 *
 * Renders the INTERIOR of the sentinel-wrapped workflow body -- the
 * lines between `# viberevert:begin:github-action-workflow` and
 * `# viberevert:end:github-action-workflow`. The github-action adapter
 * wraps this interior with sentinel markers via renderSentinelBlock()
 * for write-new / backup-and-write ops; sentinel-block-replace ops pass
 * this interior directly (installer wraps with markers).
 *
 * Discipline locked (D101.K + D101.Q + D98.M.14):
 *   - ASCII-only content (grep-safe; no smart quotes).
 *   - LF line endings via join("\n") (D101.Q).
 *   - Array-join construction per D98.M.14 -- raw multi-line template
 *     literals introduce CRLF on a CRLF checkout (Windows + autocrlf=true)
 *     and would silently drift the rendered bytes.
 *   - `permissions: { contents: read }` at the workflow level; NO
 *     `pull_request_target` trigger (fork-PR contents:write risk).
 *   - Version PINNED via cliVersion (NOT `@beta` / `latest`).
 *   - `viberevert check --since <SHA>` for both PR and push diff ranges;
 *     initial-push guard for github.event.before all-zeros.
 */

/**
 * Render the interior of the VibeRevert GitHub Action workflow body
 * (without the sentinel BEGIN/END markers). ASCII-only, LF-delimited,
 * pinned to `cliVersion`.
 */
export function renderGitHubActionWorkflowInterior(cliVersion: string): string {
  const lines: readonly string[] = [
    "# SPDX-License-Identifier: Apache-2.0",
    `# Generated by \`viberevert install --github-action\` (v${cliVersion}).`,
    "# Rerun `viberevert install --github-action` to update the pinned version.",
    "# See https://github.com/madeinplutofabio/vibe-revert for the source CLI.",
    "",
    "name: VibeRevert risk check",
    "",
    "permissions:",
    "  contents: read",
    "",
    "on:",
    "  pull_request:",
    "    branches: [main, master]",
    "  push:",
    "    branches: [main, master]",
    "",
    "jobs:",
    "  viberevert-check:",
    "    name: viberevert check",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v5",
    "        with:",
    "          fetch-depth: 0",
    "      - uses: actions/setup-node@v6",
    "        with:",
    "          node-version: 22",
    "      - name: Install pinned VibeRevert",
    `        run: npm install -g viberevert@${cliVersion}`,
    "      - name: Check PR diff",
    "        if: github.event_name == 'pull_request'",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: GitHub Actions expression syntax, not a JS template literal
    "        run: viberevert check --since ${{ github.event.pull_request.base.sha }}",
    "      - name: Check push diff",
    "        if: github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000'",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: GitHub Actions expression syntax, not a JS template literal
    "        run: viberevert check --since ${{ github.event.before }}",
    "      - name: Initial-push notice",
    "        if: github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000'",
    `        run: echo "Initial push to branch; no prior SHA to diff against. Skipping check."`,
  ];
  return lines.join("\n");
}
