// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// The selective DRY-RUN receipt mapper.
//
// PURE and total: `rollbackId` and `writtenAt` are inputs, not things generated
// here, so the same preview and plan always produce the same receipt. A mapper
// that read a clock or minted an id could not be compared against itself.
//
// =============================================================================
// No attempt marker, so no authorization to copy from
// =============================================================================
//
// The apply mapper takes every binding from the published attempt, because that
// artifact is what AUTHORIZED the mutation. A dry run authorizes nothing: it
// publishes no marker and reserves no invocation directory. So the identities
// come from the caller's verified contribution binding instead, and the
// `rollback_id` names this preview alone.
//
// That is also why the preview receipt is stored outside `rollbacks/`. See
// `selectiveDryRunReceiptPath` in `@viberevert/core`.
//
// =============================================================================
// Two cross-checks, then the planner's own ordering
// =============================================================================
//
// The receipt requires every result's group to appear in
// `resolved_change_group_ids` AND every listed group to appear in some result.
// Deriving that list from the preview would satisfy both by construction while
// silently discarding the planner's order; deriving it from the planner without
// checking could list a group nothing classified.
//
// So both are checked and the planner's list is what gets written:
//
//   1. the (path, group) PAIR sets of the preview and the plan must be equal,
//      which catches a path missing from or substituted within one group, a
//      thing a group-set comparison cannot see;
//   2. the plan's AUTHORIZED groups must equal the groups it actually
//      classified.
//
// Only then is `resolved_change_group_ids` copied from
// `plan.selectedChangeGroupIds`, preserving the order the planner chose. The
// schema's own ordering rule still applies: a planner order that violates it
// surfaces as a mapping failure rather than being silently re-sorted, because
// re-sorting would discard the very order this is preserving.
//
// =============================================================================
// Where preview and receipt genuinely diverge
// =============================================================================
//
// A preview may report one path under two groups; the receipt may not, because
// results must have unique paths in both branches. That plan is unrepresentable
// as a receipt, and the honest response is a mapping failure rather than an
// invalid or silently deduplicated artifact.

import type { SelectiveRestorePlan, SelectiveRestorePreviewResult } from "@viberevert/git";
import {
  type DryRunEligibility,
  type DryRunPathResult,
  ROLLBACK_OUT_OF_SCOPE_NOTICE,
  SELECTIVE_ROLLBACK_RECEIPT_SCHEMA_VERSION,
  type SelectiveRollbackReceipt,
  SelectiveRollbackReceiptSchema,
} from "@viberevert/session-format";
import { pairKey, sameStringSet } from "./selective-pair-key.js";
import type { ReceiptMapping } from "./selective-receipt-mapper.js";

type PreviewedResult = Extract<SelectiveRestorePreviewResult, { readonly outcome: "previewed" }>;
type DryRunReceipt = Extract<SelectiveRollbackReceipt, { readonly mode: "dry_run" }>;

export interface MapSelectiveDryRunReceiptArgs {
  readonly preview: PreviewedResult;
  readonly plan: SelectiveRestorePlan;
  /** From the caller's verified contribution binding, not from a marker. */
  readonly sessionId: string;
  readonly checkpointId: string;
  readonly contributionSha256: string;
  readonly selectors: DryRunReceipt["selectors"];
  /** Names this preview. Generated by the caller so the mapper stays pure. */
  readonly rollbackId: string;
  readonly writtenAt: string;
}

class DryRunMappingError extends Error {
  override readonly name = "DryRunMappingError";
}

const fail = (message: string): ReceiptMapping => ({
  outcome: "failed",
  cause: new DryRunMappingError(message),
});

/** Ordinal, not locale: receipt ordering must not depend on the host's locale. */
const ordinal = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

const byPathThenGroup = (a: DryRunPathResult, b: DryRunPathResult): number =>
  ordinal(a.path, b.path) || ordinal(a.change_group_id, b.change_group_id);

/** `restored` and `already_at_before` mean "would be" in a dry run. */
const isRestorable = (result: DryRunPathResult): boolean =>
  result.outcome === "restored" || result.outcome === "already_at_before";

/**
 * Three-way, not two.
 *
 * `every` alone calls an empty selection eligible, which is a different claim
 * from having nothing to do, and the schema couples `empty_selection` to both
 * the results and the resolved groups being empty.
 */
function eligibilityOf(results: readonly DryRunPathResult[]): DryRunEligibility {
  if (results.length === 0) return "empty_selection";
  return results.every(isRestorable) ? "eligible" : "ineligible";
}

/**
 * Unique (path, group) pairs, or `null` when a PATH repeats.
 *
 * Paths are checked independently of pairs because the receipt forbids
 * duplicate paths outright: one path under two groups is a valid preview and an
 * unrepresentable receipt, and reporting that as a pair mismatch would name the
 * wrong problem.
 */
function uniquePairs(
  items: readonly { readonly path: string; readonly changeGroupId: string }[],
): ReadonlySet<string> | null {
  const paths = new Set<string>();
  const pairs = new Set<string>();
  for (const item of items) {
    if (paths.has(item.path)) return null;
    paths.add(item.path);
    pairs.add(pairKey(item.path, item.changeGroupId));
  }
  return pairs;
}

function mapInternal(args: MapSelectiveDryRunReceiptArgs): ReceiptMapping {
  const { preview, plan, selectors, rollbackId, writtenAt } = args;

  const previewPairs = uniquePairs(preview.paths);
  if (previewPairs === null) {
    return fail(
      "the preview reports one path under more than one change group, which a receipt cannot express: results must have unique paths",
    );
  }
  const planPairs = uniquePairs(plan.classifications);
  if (planPairs === null) {
    return fail(
      "the plan carries a duplicated classification path, which a receipt cannot express",
    );
  }
  if (!sameStringSet(previewPairs, planPairs)) {
    return fail("the preview's (path, change group) pairs differ from the plan's classifications");
  }

  const classifiedGroups = new Set(plan.classifications.map((c) => c.changeGroupId));
  const authorizedGroups = new Set(plan.selectedChangeGroupIds);
  if (!sameStringSet(authorizedGroups, classifiedGroups)) {
    return fail("the plan authorizes change groups it did not classify, or the reverse");
  }

  const results = preview.paths
    .map(
      (p): DryRunPathResult => ({
        path: p.path,
        change_group_id: p.changeGroupId,
        outcome: p.outcome,
        ...(p.detail === undefined ? {} : { reason: p.detail }),
      }),
    )
    .sort(byPathThenGroup);

  const candidate = {
    schema_version: SELECTIVE_ROLLBACK_RECEIPT_SCHEMA_VERSION,
    mode: "dry_run",
    rollback_id: rollbackId,
    session_id: args.sessionId,
    checkpoint_id: args.checkpointId,
    contribution_sha256: args.contributionSha256,
    selectors,
    // The planner's own order, proven complete by the pair check above.
    resolved_change_group_ids: [...plan.selectedChangeGroupIds],
    results,
    eligibility: eligibilityOf(results),
    written_at: writtenAt,
    out_of_scope_notice: ROLLBACK_OUT_OF_SCOPE_NOTICE,
  };

  const parsed = SelectiveRollbackReceiptSchema.safeParse(candidate);
  return parsed.success
    ? { outcome: "mapped", receipt: parsed.data }
    : { outcome: "failed", cause: parsed.error };
}

/**
 * Map a completed preview into a dry-run receipt.
 *
 * NEVER THROWS. The wrapper is what makes that true rather than aspirational: a
 * getter or a future refinement can throw, and the caller must still get a value
 * it can report.
 */
export function mapSelectiveDryRunReceipt(args: MapSelectiveDryRunReceiptArgs): ReceiptMapping {
  try {
    return mapInternal(args);
  } catch (cause) {
    return { outcome: "failed", cause };
  }
}
