// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// The selective DRY-RUN receipt mapper.
//
// PURE and total: `rollbackId` and `writtenAt` are inputs, not things generated
// here, so the same preview and plan always produce the same receipt. A mapper
// that read a clock or minted an id could not be compared against itself.
//
// =============================================================================
// No attempt marker, so no authorization to copy from
// =============================================================================
//
// The apply mapper takes every binding from the published attempt, because that
// artifact is what AUTHORIZED the mutation. A dry run authorizes nothing: it
// publishes no marker and reserves no invocation directory. So the identities
// come from the caller's verified contribution binding instead, and the
// `rollback_id` names this preview alone.
//
// That is also why the preview receipt is stored outside `rollbacks/`. See
// `selectiveDryRunReceiptPath` in `@viberevert/core`.
//
// =============================================================================
// Two cross-checks, then the planner's own ordering
// =============================================================================
//
// The receipt requires every result's group to appear in
// `resolved_change_group_ids` AND every listed group to appear in some result.
// Deriving that list from the preview would satisfy both by construction while
// silently discarding the planner's order; deriving it from the planner without
// checking could list a group nothing classified.
//
// So both are checked and the planner's list is what gets written:
//
//   1. the (path, group) PAIR sets of the preview and the plan must be equal,
//      which catches a path missing from or substituted within one group, a
//      thing a group-set comparison cannot see;
//   2. the plan's AUTHORIZED groups must equal the groups it actually
//      classified.
//
// Only then is `resolved_change_group_ids` copied from
// `plan.selectedChangeGroupIds`, preserving the order the planner chose. The
// schema's own ordering rule still applies: a planner order that violates it
// surfaces as a mapping failure rather than being silently re-sorted, because
// re-sorting would discard the very order this is preserving.
//
// =============================================================================
// Where preview and receipt genuinely diverge
// =============================================================================
//
// A preview may report one path under two groups; the receipt may not, because
// results must have unique paths in both branches. That plan is unrepresentable
// as a receipt, and the honest response is a mapping failure rather than an
// invalid or silently deduplicated artifact.
//
// =============================================================================
// Two entry points, one assembler
// =============================================================================
//
// `mapSelectiveDryRunReceipt` takes a preview and the plan it was computed
// from. `mapEmptySelectiveDryRunReceipt` takes neither, because a selection
// that resolved to nothing never reached the planner. Both assemble through
// `assembleReceipt`, so `eligibility` is derived by one rule and the schema is
// consulted once.
//
// The empty case gets its own entry point rather than empty arrays through the
// first, because there is no plan to pass. Constructing one here would mean
// stating capabilities nobody probed, and an unexamined claim in a persisted
// artifact is worse than a second function signature.

import type { SelectiveRestorePlan, SelectiveRestorePreviewResult } from "@viberevert/git";
import {
  type DryRunEligibility,
  type DryRunPathResult,
  ROLLBACK_OUT_OF_SCOPE_NOTICE,
  SELECTIVE_ROLLBACK_RECEIPT_SCHEMA_VERSION,
  type SelectiveRollbackReceipt,
  SelectiveRollbackReceiptSchema,
} from "@viberevert/session-format";
import { pairKey, sameStringSet } from "./selective-pair-key.js";
import type { ReceiptMapping } from "./selective-receipt-mapper.js";

type PreviewedResult = Extract<SelectiveRestorePreviewResult, { readonly outcome: "previewed" }>;
type DryRunReceipt = Extract<SelectiveRollbackReceipt, { readonly mode: "dry_run" }>;

/**
 * Everything a dry-run receipt needs that does not come from a preview.
 *
 * Shared by both entry points, so an empty selection's receipt is identified
 * exactly the way a previewed one is.
 */
export interface SelectiveDryRunReceiptIdentity {
  /** From the caller's verified contribution binding, not from a marker. */
  readonly sessionId: string;
  readonly checkpointId: string;
  readonly contributionSha256: string;
  readonly selectors: DryRunReceipt["selectors"];
  /** Names this preview. Generated by the caller so the mapper stays pure. */
  readonly rollbackId: string;
  readonly writtenAt: string;
}

export interface MapSelectiveDryRunReceiptArgs extends SelectiveDryRunReceiptIdentity {
  readonly preview: PreviewedResult;
  readonly plan: SelectiveRestorePlan;
}

class DryRunMappingError extends Error {
  override readonly name = "DryRunMappingError";
}

const fail = (message: string): ReceiptMapping => ({
  outcome: "failed",
  cause: new DryRunMappingError(message),
});

/** Ordinal, not locale: receipt ordering must not depend on the host's locale. */
const ordinal = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

const byPathThenGroup = (a: DryRunPathResult, b: DryRunPathResult): number =>
  ordinal(a.path, b.path) || ordinal(a.change_group_id, b.change_group_id);

/** `restored` and `already_at_before` mean "would be" in a dry run. */
const isRestorable = (result: DryRunPathResult): boolean =>
  result.outcome === "restored" || result.outcome === "already_at_before";

/**
 * Three-way, not two.
 *
 * `every` alone calls an empty selection eligible, which is a different claim
 * from having nothing to do, and the schema couples `empty_selection` to both
 * the results and the resolved groups being empty.
 */
function eligibilityOf(results: readonly DryRunPathResult[]): DryRunEligibility {
  if (results.length === 0) return "empty_selection";
  return results.every(isRestorable) ? "eligible" : "ineligible";
}

/**
 * Unique (path, group) pairs, or `null` when a PATH repeats.
 *
 * Paths are checked independently of pairs because the receipt forbids
 * duplicate paths outright: one path under two groups is a valid preview and an
 * unrepresentable receipt, and reporting that as a pair mismatch would name the
 * wrong problem.
 */
function uniquePairs(
  items: readonly { readonly path: string; readonly changeGroupId: string }[],
): ReadonlySet<string> | null {
  const paths = new Set<string>();
  const pairs = new Set<string>();
  for (const item of items) {
    if (paths.has(item.path)) return null;
    paths.add(item.path);
    pairs.add(pairKey(item.path, item.changeGroupId));
  }
  return pairs;
}

/**
 * The ONE place a dry-run receipt is assembled and validated.
 *
 * Both entry points arrive here, so `eligibility` is derived by one rule and
 * the schema is consulted once. A second assembler for the empty case could
 * satisfy the schema's `empty_selection` coupling by accident today and drift
 * from it later, which is exactly the coupling the schema exists to hold.
 */
function assembleReceipt(
  identity: SelectiveDryRunReceiptIdentity,
  results: readonly DryRunPathResult[],
  resolvedChangeGroupIds: readonly string[],
): ReceiptMapping {
  const candidate = {
    schema_version: SELECTIVE_ROLLBACK_RECEIPT_SCHEMA_VERSION,
    mode: "dry_run",
    rollback_id: identity.rollbackId,
    session_id: identity.sessionId,
    checkpoint_id: identity.checkpointId,
    contribution_sha256: identity.contributionSha256,
    selectors: identity.selectors,
    resolved_change_group_ids: [...resolvedChangeGroupIds],
    results: [...results],
    eligibility: eligibilityOf(results),
    written_at: identity.writtenAt,
    out_of_scope_notice: ROLLBACK_OUT_OF_SCOPE_NOTICE,
  };

  const parsed = SelectiveRollbackReceiptSchema.safeParse(candidate);
  return parsed.success
    ? { outcome: "mapped", receipt: parsed.data }
    : { outcome: "failed", cause: parsed.error };
}

function mapInternal(args: MapSelectiveDryRunReceiptArgs): ReceiptMapping {
  const { preview, plan } = args;

  const previewPairs = uniquePairs(preview.paths);
  if (previewPairs === null) {
    return fail(
      "the preview reports one path under more than one change group, which a receipt cannot express: results must have unique paths",
    );
  }
  const planPairs = uniquePairs(plan.classifications);
  if (planPairs === null) {
    return fail(
      "the plan carries a duplicated classification path, which a receipt cannot express",
    );
  }
  if (!sameStringSet(previewPairs, planPairs)) {
    return fail("the preview's (path, change group) pairs differ from the plan's classifications");
  }

  const classifiedGroups = new Set(plan.classifications.map((c) => c.changeGroupId));
  const authorizedGroups = new Set(plan.selectedChangeGroupIds);
  if (!sameStringSet(authorizedGroups, classifiedGroups)) {
    return fail("the plan authorizes change groups it did not classify, or the reverse");
  }

  const results = preview.paths
    .map(
      (p): DryRunPathResult => ({
        path: p.path,
        change_group_id: p.changeGroupId,
        outcome: p.outcome,
        ...(p.detail === undefined ? {} : { reason: p.detail }),
      }),
    )
    .sort(byPathThenGroup);

  // The planner's own order, proven complete by the pair check above.
  return assembleReceipt(args, results, plan.selectedChangeGroupIds);
}

/**
 * Map a completed preview into a dry-run receipt.
 *
 * NEVER THROWS. The wrapper is what makes that true rather than aspirational: a
 * getter or a future refinement can throw, and the caller must still get a value
 * it can report.
 */
export function mapSelectiveDryRunReceipt(args: MapSelectiveDryRunReceiptArgs): ReceiptMapping {
  try {
    return mapInternal(args);
  } catch (cause) {
    return { outcome: "failed", cause };
  }
}

/**
 * Map the receipt for a selection that resolved to NO change group.
 *
 * A separate entry point rather than a plan-and-preview pair of empty arrays,
 * because there is no plan: resolution stops before one is built, and an empty
 * `SelectiveRestorePlan` assembled here would have to state capabilities
 * nobody probed. Passing no plan says that honestly; fabricating one would put
 * an unexamined claim into an artifact.
 *
 * The receipt is a real result, not a placeholder. `empty_selection` is a
 * distinct eligibility precisely so "the selectors matched nothing" has one
 * spelling, and a dry run that wrote nothing would leave the user inferring it
 * from silence.
 */
export function mapEmptySelectiveDryRunReceipt(
  identity: SelectiveDryRunReceiptIdentity,
): ReceiptMapping {
  try {
    return assembleReceipt(identity, [], []);
  } catch (cause) {
    return { outcome: "failed", cause };
  }
}
