// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Unit tests for packages/reporters/src/fix-prompt-render.ts
// (M E Step 2 file 5 — fix-prompt renderer assembly + barrel surface).
//
// Seven sections covering distinct responsibilities:
//
//   1. ASSEMBLY & STRUCTURAL INVARIANTS — renderFixPrompt assembles
//      the seven D85 sections in the locked order, separated by
//      exactly one blank line, with exactly one trailing LF and
//      zero `\r` characters. Determinism is locked: same input →
//      byte-identical output across repeated calls. These are the
//      contract D81 + D85 invariants this file polices.
//
//   2. TASK SECTION CONDITIONAL (D85.3) — when `file.report.task`
//      is present + non-empty after inline normalization, the
//      `Task: <value>` line appears between source attribution and
//      repo context; otherwise it is omitted entirely (no
//      placeholder section, no spurious blank-line-only gap).
//
//   3. SOURCE-KIND BRANCHING (D85.6) — session-bound emits the
//      `viberevert rollback <session_id>` next-steps variant;
//      ad-hoc emits the git/checkpoint variant (rollback is
//      session-scoped and would not apply).
//
//   4. EMPTY-FINDINGS DEFENSIVE CASE — renderer renders a valid
//      `## Findings (0)` section with no per-finding blocks; never
//      throws. The CLI enforces the empty-findings refusal BEFORE
//      reaching the renderer per D86, but the renderer stays
//      defensively correct so the business-rule-vs-rendering
//      boundary is clean.
//
//   5. PRODUCT-VERSION + FOOTER (D85.9) — productVersion threads
//      through to the footer's `Generated by VibeRevert v<version>`
//      line; the report_id appears in BOTH the source-attribution
//      line and the footer; file.written_at appears in the footer's
//      `Report written at <written_at>` line.
//
//   6. BARREL SMOKE — renderFixPrompt is reachable through
//      ../src/index.js (the package's public barrel); M C report
//      and M D receipt exports remain callable (regression gate
//      against accidental displacement during the M E barrel
//      update).
//
//   7. HELPER-LEAKAGE LOCK — every export from
//      fix-prompt-template.ts (normalizeInline / normalizeBlock /
//      sortFindings / truncateFindings / renderPreamble / ... /
//      RECOMMENDATION_FALLBACK_LOW / MAX_FINDINGS / ...) MUST NOT
//      appear on the barrel. The barrel's only fix-prompt surface
//      is `renderFixPrompt` + `FixPromptRenderInput`. Catches
//      accidental promotion of file-local helpers to the public
//      surface; generated one-per-name so each failure names the
//      leaked helper directly.
//
// Template-branch smoke coverage: session-bound vs ad-hoc, task
// present vs absent, footer/version threading, empty findings, and
// section order. Detailed risk-level sorting, recommendation
// fallback, summary rendering, normalization, truncation, and
// evidence rendering live in fix-prompt-template.test.ts.
//
// Fixture-validity discipline: every ReportFile fixture flows through
// ReportFileSchema.parse via makeReportFile, mirroring the receipt
// fixture-validity pattern from receipt-render.test.ts. Risk level is
// INFERRED from the contained findings (max by rank) rather than
// hard-defaulted to "low" — keeps fixtures semantically honest if
// SessionReportSchema later adds a risk_level/results consistency
// refine. `rollback_available` mirrors `kind === "session_bound"` for
// the same semantic-honesty reason (ad-hoc reports have no owning
// session and cannot be rolled back per M D).

import type { CheckResult, ReportFile, RiskLevel, SessionReport } from "@viberevert/session-format";
import { REPORT_FILE_SCHEMA_VERSION, ReportFileSchema } from "@viberevert/session-format";
import { describe, expect, it } from "vitest";

import { renderFixPrompt } from "../src/fix-prompt-render.js";
import { PREAMBLE_PARAGRAPHS } from "../src/fix-prompt-template.js";
import type { FixPromptRenderInput } from "../src/fix-prompt-types.js";
import * as ReportersBarrel from "../src/index.js";

// =============================================================================
// Test fixtures (per-file duplication intentional, matching the
// existing reporter test convention)
// =============================================================================

const VALID_ULID = "01ABCDEFGHJKMNPQRSTVWXYZ23";
const SESSION_ID = `sess_${VALID_ULID}`;
const REPORT_ID = `rpt_${VALID_ULID}`;
const FIXED_SHA = "abcdef0123456789abcdef0123456789abcdef01";
const FIXED_TIME = "2026-01-01T00:00:00Z";

/**
 * Compute the maximum risk level present in a set of findings (low <
 * medium < high < critical). Used by `makeReportFile` to keep the
 * fixture's report-level `risk_level` semantically consistent with
 * the contained findings — important defense if SessionReportSchema
 * later adds a "risk_level must be >= max(results.level)" refine.
 *
 * Empty results array → "low" (no findings means the report's overall
 * risk is the floor value; matches the convention used elsewhere in
 * the codebase for empty-findings reports).
 */
function inferRiskLevel(results: readonly CheckResult[]): RiskLevel {
  const rank: Record<RiskLevel, number> = {
    low: 0,
    medium: 1,
    high: 2,
    critical: 3,
  };

  let max: RiskLevel = "low";
  for (const result of results) {
    if (rank[result.level] > rank[max]) {
      max = result.level;
    }
  }
  return max;
}

function makeResult(opts: {
  level: RiskLevel;
  id?: string;
  category?: string;
  title?: string;
  message?: string;
  recommendation?: string;
}): CheckResult {
  const requiresReco = opts.level === "high" || opts.level === "critical";
  const reco = opts.recommendation ?? (requiresReco ? "Test recommendation." : undefined);
  const base = {
    id: opts.id ?? "test.id",
    category: opts.category ?? "test",
    level: opts.level,
    confidence: "medium" as const,
    title: opts.title ?? "Test title",
    message: opts.message ?? "Test message",
    evidence: [{ detail: "test detail" }],
  };
  return reco === undefined ? base : { ...base, recommendation: reco };
}

function makeReportFile(
  opts: {
    kind?: "session_bound" | "ad_hoc";
    results?: readonly CheckResult[];
    detectedFrameworks?: readonly string[];
    riskLevel?: RiskLevel;
    summary?: string;
    task?: string;
    sinceKind?: ReportFile["since_kind"];
    sinceRef?: string;
  } = {},
): ReportFile {
  const kind = opts.kind ?? "session_bound";
  const reportId = kind === "session_bound" ? SESSION_ID : REPORT_ID;
  // Default since_kind matches the locked refine: session_bound ↔
  // {session_id, active_session}; ad_hoc ↔ {checkpoint_id,
  // checkpoint_name, git_ref}. Defaults pick one from each set.
  const sinceKind: ReportFile["since_kind"] =
    opts.sinceKind ?? (kind === "session_bound" ? "session_id" : "checkpoint_name");
  const sinceRef = opts.sinceRef ?? (kind === "session_bound" ? SESSION_ID : "baseline");

  // Compute results first so risk_level can be INFERRED from them.
  // Caller can still override via `opts.riskLevel` (e.g., to test a
  // report whose declared risk exceeds its contained findings).
  const results = opts.results ? [...opts.results] : [];
  const riskLevel = opts.riskLevel ?? inferRiskLevel(results);

  const report: SessionReport = {
    schema_version: "1.0",
    session_id: reportId,
    started_at: FIXED_TIME,
    detected_frameworks: opts.detectedFrameworks ? [...opts.detectedFrameworks] : [],
    risk_level: riskLevel,
    results,
    changed_files: [],
    // Ad-hoc reports have no owning session and cannot be rolled
    // back per M D — `rollback_available` mirrors `kind` so the
    // fixture stays semantically honest.
    rollback_available: kind === "session_bound",
    ...(opts.task !== undefined ? { task: opts.task } : {}),
    ...(opts.summary !== undefined ? { summary: opts.summary } : {}),
  };
  const file = {
    schema_version: REPORT_FILE_SCHEMA_VERSION,
    kind,
    report_id: reportId,
    since_kind: sinceKind,
    since_ref: sinceRef,
    since_resolved_sha: FIXED_SHA,
    written_at: FIXED_TIME,
    report,
  };
  return ReportFileSchema.parse(file);
}

function makeRenderInput(opts: {
  file: ReportFile;
  productVersion?: string;
}): FixPromptRenderInput {
  return {
    file: opts.file,
    productVersion: opts.productVersion ?? "0.7.0-beta",
  };
}

// =============================================================================
// SECTION 1: assembly & structural invariants (D81 + D85)
// =============================================================================

describe("renderFixPrompt — assembly & structural invariants", () => {
  it("output starts with the locked three-paragraph preamble verbatim", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    const preamble = PREAMBLE_PARAGRAPHS.join("\n\n");
    expect(out.startsWith(`${preamble}\n\n`)).toBe(true);
  });

  it("sections appear in the locked D85 order (preamble → source → repo → findings → next-steps → footer)", () => {
    // No `task` supplied, so the optional task section is omitted —
    // this assertion verifies the base six-section order with the
    // optional task section absent.
    const file = makeReportFile({
      results: [makeResult({ level: "medium", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));

    const idxPreamble = out.indexOf(PREAMBLE_PARAGRAPHS[0] ?? "");
    const idxSource = out.indexOf("Source report:");
    const idxRepo = out.indexOf("Frameworks:");
    const idxFindings = out.indexOf("## Findings");
    const idxNextSteps = out.indexOf("After addressing the findings");
    const idxFooter = out.indexOf("\n--\n");

    expect(idxPreamble).toBe(0);
    expect(idxSource).toBeGreaterThan(idxPreamble);
    expect(idxRepo).toBeGreaterThan(idxSource);
    expect(idxFindings).toBeGreaterThan(idxRepo);
    expect(idxNextSteps).toBeGreaterThan(idxFindings);
    expect(idxFooter).toBeGreaterThan(idxNextSteps);
  });

  it("sections separated by exactly one blank line; no `\\n\\n\\n` runs anywhere", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
      task: "fix the bug",
      detectedFrameworks: ["pnpm", "vitest"],
      summary: "one finding",
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes("\n\n\n")).toBe(false);
  });

  it("output ends with exactly one trailing LF (never zero, never two)", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.endsWith("\n")).toBe(true);
    expect(out.endsWith("\n\n")).toBe(false);
  });

  it("output contains LF line endings only — no `\\r` characters anywhere (CRLF / lone CR in dynamic content normalized away)", () => {
    // Even when dynamic content carries CRLF (Windows) or lone CR
    // (Mac classic) line endings, the renderer's inline + block
    // normalizers strip them to LF. The rendered prompt's "LF only"
    // promise (contract Rendered-output-format section) is global.
    const file = makeReportFile({
      results: [
        makeResult({
          level: "high",
          id: "ck.a",
          title: "Windows line ending\r\nshould be normalized",
          message: "Mac classic\rline ending\r\nmixed",
        }),
      ],
      task: "task\r\nwith CRLF",
      summary: "summary with\r\nCRLF inside",
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes("\r")).toBe(false);
  });

  it("same input produces byte-identical output across repeated calls (determinism)", () => {
    // Two calls with the SAME input must return strictly-equal
    // strings. Catches a future template helper that sneaks in a
    // clock read / random read / ulid call (D29 + D90.5 prohibit
    // these, but a behavioral lock here adds a second safety net).
    const file = makeReportFile({
      results: [
        makeResult({ level: "high", id: "ck.b", title: "B" }),
        makeResult({ level: "critical", id: "ck.a", title: "A" }),
        makeResult({ level: "medium", id: "ck.c", title: "C" }),
      ],
      detectedFrameworks: ["pnpm", "vitest"],
      task: "deterministic fix",
      summary: "three findings",
    });
    const input = makeRenderInput({ file });
    const out1 = renderFixPrompt(input);
    const out2 = renderFixPrompt(input);
    expect(out1).toBe(out2);
  });
});

// =============================================================================
// SECTION 2: task section conditional inclusion (D85.3)
// =============================================================================

describe("renderFixPrompt — task section (D85.3 conditional inclusion)", () => {
  it("renders `Task: <value>` between source attribution and repo context when file.report.task is non-empty", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
      task: "fix the failing test",
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    const idxSource = out.indexOf("Source report:");
    const idxTask = out.indexOf("Task: fix the failing test");
    const idxRepo = out.indexOf("Frameworks:");
    expect(idxTask).toBeGreaterThan(idxSource);
    expect(idxRepo).toBeGreaterThan(idxTask);
  });

  it("omits the Task section entirely when file.report.task is undefined (no placeholder, no spurious blank gap)", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
      // task NOT supplied → undefined on the optional field
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes("Task:")).toBe(false);
    // Absent-section join MUST NOT create a triple-newline run.
    expect(out.includes("\n\n\n")).toBe(false);
  });

  it("normalizes a multi-line task to a single inline value before rendering", () => {
    // Inline normalization (D85.7): CRLF/lone-CR → LF → collapse
    // `\n` runs to space → trim. This test uses bare `\n` since
    // schema-level `nonBlankString` permits inner newlines.
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
      task: "line one\nline two",
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes("Task: line one line two")).toBe(true);
  });

  // Note: a whitespace-only task (e.g. "   ") would fail the schema's
  // `nonBlankString` constraint, so the "task normalizes to empty →
  // omitted" branch cannot be exercised through a schema-validated
  // fixture. That branch is hammered in fix-prompt-template.test.ts
  // (file 6) via direct `renderTaskSection` calls with hand-built
  // pre-schema inputs.
});

// =============================================================================
// SECTION 3: source-kind branching for next-steps (D85.6)
// =============================================================================

describe("renderFixPrompt — next-steps variant (D85.6)", () => {
  it("session_bound emits the `viberevert rollback <session_id>` clause", () => {
    const file = makeReportFile({
      kind: "session_bound",
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes(`recover with \`viberevert rollback ${SESSION_ID}\``)).toBe(true);
  });

  it("ad_hoc emits the `recover with git or a prior checkpoint; rollback is session-scoped.` clause and NO rollback command", () => {
    const file = makeReportFile({
      kind: "ad_hoc",
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(
      out.includes("recover with git or a prior checkpoint; rollback is session-scoped."),
    ).toBe(true);
    // Defensive: the session-bound rollback clause MUST NOT appear
    // anywhere in an ad_hoc prompt (it would mislead the agent —
    // rollback is session-scoped per D80 / M D).
    expect(out.includes("viberevert rollback ")).toBe(false);
  });
});

// =============================================================================
// SECTION 4: empty-findings defensive case (CLI refuses; renderer renders)
// =============================================================================

describe("renderFixPrompt — empty-findings defensive case", () => {
  it("renders `## Findings (0)` with no per-finding blocks and never throws", () => {
    // Per D86 the CLI refuses BEFORE calling the renderer when
    // results is empty (and additionally removes any stale sibling
    // fix-prompt.txt). The renderer stays defensively correct so
    // the business-rule-vs-rendering boundary is clean — a future
    // caller that bypasses the CLI refusal gets a structurally
    // valid prompt with zero findings rather than a thrown error.
    const file = makeReportFile({ results: [] });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes("## Findings (0)")).toBe(true);
    // No per-finding header anywhere in the output.
    expect(out.includes("### [")).toBe(false);
  });
});

// =============================================================================
// SECTION 5: productVersion threading + footer (D85.9)
// =============================================================================

describe("renderFixPrompt — productVersion threading and footer (D85.9)", () => {
  it("productVersion appears in the footer's `Generated by VibeRevert v<version>` line", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file, productVersion: "9.9.9-test" }));
    expect(out.includes("Generated by VibeRevert v9.9.9-test from report")).toBe(true);
  });

  it("report_id appears in BOTH the source-attribution line and the footer (ad_hoc rpt_<ULID>)", () => {
    const file = makeReportFile({
      kind: "ad_hoc",
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    const idxSourceLine = out.indexOf(`Source report: ${REPORT_ID}`);
    const idxFooterLine = out.indexOf(`from report ${REPORT_ID}.`);
    expect(idxSourceLine).toBeGreaterThan(-1);
    expect(idxFooterLine).toBeGreaterThan(idxSourceLine);
  });

  it("file.written_at appears in the footer's `Report written at <written_at>` line", () => {
    // The footer timestamp is the SOURCE REPORT's written_at, NOT
    // the prompt-generation time. The renderer never samples its
    // own clock (D29 / D90.5).
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const out = renderFixPrompt(makeRenderInput({ file }));
    expect(out.includes(`Report written at ${FIXED_TIME}.`)).toBe(true);
  });
});

// =============================================================================
// SECTION 6: barrel smoke (regression gate against displacement)
// =============================================================================

describe("@viberevert/reporters barrel — fix-prompt surface smoke", () => {
  it("renderFixPrompt is exported and callable from ../src/index.js (non-empty string)", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high", id: "ck.a", title: "A" })],
    });
    const input = makeRenderInput({ file });
    expect(typeof ReportersBarrel.renderFixPrompt).toBe("function");
    const out = ReportersBarrel.renderFixPrompt(input);
    expect(typeof out).toBe("string");
    expect(out.length).toBeGreaterThan(0);
  });

  it("M C report symbols remain callable through the barrel (regression gate against M E displacement)", () => {
    expect(typeof ReportersBarrel.render).toBe("function");
    expect(typeof ReportersBarrel.renderJson).toBe("function");
    expect(typeof ReportersBarrel.renderMarkdown).toBe("function");
    expect(typeof ReportersBarrel.renderTerminal).toBe("function");
    expect(typeof ReportersBarrel.applyThreshold).toBe("function");
  });

  it("M D receipt symbols remain callable through the barrel (regression gate against M E displacement)", () => {
    expect(typeof ReportersBarrel.renderReceipt).toBe("function");
    expect(typeof ReportersBarrel.renderReceiptJson).toBe("function");
    expect(typeof ReportersBarrel.renderReceiptMarkdown).toBe("function");
    expect(typeof ReportersBarrel.renderReceiptTerminal).toBe("function");
  });
});

// =============================================================================
// SECTION 7: helper-leakage lock — template helpers NOT in the barrel
// =============================================================================

describe("@viberevert/reporters barrel — fix-prompt helper-leakage lock", () => {
  // Every export from fix-prompt-template.ts is INTERNAL. The
  // barrel's only fix-prompt surface is `renderFixPrompt` +
  // `FixPromptRenderInput`. If a future maintainer accidentally
  // re-exports a template helper through the barrel — turning an
  // internal contract knob into part of the public API — this
  // lock fires. One assertion per name so each failure names the
  // leaked helper directly (mirrors receipt-render.test.ts's
  // per-name generated lock).

  const FORBIDDEN_FIX_PROMPT_HELPER_NAMES = [
    // Constants
    "PREAMBLE_PARAGRAPHS",
    "MAX_FINDINGS",
    "RECOMMENDATION_FALLBACK_HIGH",
    "RECOMMENDATION_FALLBACK_LOW",
    // Normalization helpers
    "normalizeInline",
    "normalizeBlock",
    // Enum gate
    "validateAndUppercaseLevel",
    // Sort + truncation
    "sortFindings",
    "truncateFindings",
    // Per-section render helpers
    "renderPreamble",
    "renderSourceAttribution",
    "renderTaskSection",
    "renderRepoContext",
    "renderEvidenceEntry",
    "renderRecommendation",
    "renderFinding",
    "renderFindingsSection",
    "renderNextSteps",
    "renderFooter",
  ];

  for (const helperName of FORBIDDEN_FIX_PROMPT_HELPER_NAMES) {
    it(`${helperName} is NOT exported from the barrel`, () => {
      expect(ReportersBarrel).not.toHaveProperty(helperName);
    });
  }
});
