// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Unit tests for packages/reporters/src/markdown.ts
// (Step 8 Phase C file 16).
//
// Coverage strategy:
//
//   1. HEADING STRUCTURE — H1 "VibeRevert Report", H2 "Summary",
//      H2 "Findings", H2 "Changed Files".
//
//   2. SUMMARY BULLETS — Report ID, Kind, Since, etc. as bullet
//      list; optional fields shown only when present.
//
//   3. FINDINGS — empty section "No findings." placeholder;
//      single-finding format `**[LEVEL]** title (category,
//      confidence)` + message + fenced evidence + Recommendation;
//      multi-evidence rendering; category H3 ASCII-asc order
//      regression (engine produces non-alphabetical category order
//      when level varies).
//
//   4. CHANGED FILES — empty "No changed files." placeholder;
//      bullet `- \`S\` path — tags — LEVEL` format; rename suffix.
//
//   5. THRESHOLD INTEGRATION — applyThreshold called before
//      formatting; low findings disappear at threshold "high".
//
//   6. LOCKED FOOTER — "Generated by VibeRevert v<version>."
//      appears verbatim with productVersion (markdown-only footer
//      per D45).
//
//   7. INLINE MARKDOWN ESCAPING — user-derived text (title,
//      message, task, etc.) escapes backticks/asterisks/
//      underscores/brackets; evidence content NOT escaped (lives
//      inside fenced code blocks).
//
//   8. DYNAMIC BACKTICK FENCE — evidence containing triple
//      backticks uses a 4-backtick fence to avoid breakout
//      (per CommonMark §4.5).
//
// NOTE ON UNDERSCORE-ESCAPED ASSERTIONS: several fixtures use
// values that contain underscores (e.g., kind "session_bound",
// sentinel title "ABOVE_THRESHOLD_TITLE"). The renderer's
// `inlineMarkdown` helper escapes underscores per CommonMark
// emphasis rules, so the rendered output contains `session\_bound`
// and `ABOVE\_THRESHOLD\_TITLE`. Assertions match the rendered
// (escaped) form; the unescaped form would never appear in real
// markdown output.

import type {
  ChangedFile,
  CheckResult,
  ReportFile,
  RiskLevel,
  SessionReport,
} from "@viberevert/session-format";
import { describe, expect, it } from "vitest";

import type { RenderInput } from "../src/index.js";
import { renderMarkdown } from "../src/markdown.js";

// =============================================================================
// Test fixture helpers
// =============================================================================

const VALID_ULID = "01ABCDEFGHJKMNPQRSTVWXYZ23";
const SESSION_ID = `sess_${VALID_ULID}`;

function makeResult(opts: {
  level: RiskLevel;
  category?: string;
  id?: string;
  title?: string;
  message?: string;
  recommendation?: string;
  evidence?: readonly { file?: string; line?: number; command?: string; detail: string }[];
}): CheckResult {
  const requiresReco = opts.level === "high" || opts.level === "critical";
  const reco = opts.recommendation ?? (requiresReco ? "Test recommendation." : undefined);
  const evidence = opts.evidence ?? [{ detail: "test detail" }];
  const base = {
    id: opts.id ?? "test.id",
    category: opts.category ?? "test",
    level: opts.level,
    confidence: "medium" as const,
    title: opts.title ?? "Test title",
    message: opts.message ?? "Test message",
    evidence: [...evidence],
  };
  return reco === undefined ? base : { ...base, recommendation: reco };
}

function makeReportFile(
  opts: {
    results?: readonly CheckResult[];
    summary?: string;
    riskLevel?: RiskLevel;
    task?: string;
    detectedFrameworks?: readonly string[];
    changedFiles?: readonly ChangedFile[];
  } = {},
): ReportFile {
  const reportBase: SessionReport = {
    schema_version: "1.0",
    session_id: SESSION_ID,
    started_at: "2026-01-01T00:00:00Z",
    detected_frameworks: [...(opts.detectedFrameworks ?? [])],
    risk_level: opts.riskLevel ?? "low",
    results: [...(opts.results ?? [])],
    changed_files: [...(opts.changedFiles ?? [])],
    rollback_available: true,
  };
  const report: SessionReport = {
    ...reportBase,
    ...(opts.summary !== undefined ? { summary: opts.summary } : {}),
    ...(opts.task !== undefined ? { task: opts.task } : {}),
  };
  return {
    schema_version: "1.0",
    kind: "session_bound",
    report_id: SESSION_ID,
    since_kind: "session_id",
    since_ref: SESSION_ID,
    since_resolved_sha: "0000000000000000000000000000000000000000",
    written_at: "2026-01-01T00:00:00Z",
    report,
  };
}

function makeRenderInput(opts: {
  file: ReportFile;
  threshold?: RiskLevel;
  productVersion?: string;
}): RenderInput {
  const base = { file: opts.file, productVersion: opts.productVersion ?? "0.7.0-beta" };
  return opts.threshold === undefined ? base : { ...base, threshold: opts.threshold };
}

// =============================================================================
// SECTION 1: heading structure
// =============================================================================

describe("renderMarkdown — heading structure", () => {
  it("renders H1 title and H2 sections (Summary, Findings, Changed Files)", () => {
    const output = renderMarkdown(makeRenderInput({ file: makeReportFile() }));
    expect(output).toContain("# VibeRevert Report");
    expect(output).toContain("## Summary");
    expect(output).toContain("## Findings");
    expect(output).toContain("## Changed Files");
  });
});

// =============================================================================
// SECTION 2: summary bullets
// =============================================================================

describe("renderMarkdown — summary bullets", () => {
  it("renders required summary bullets; optional fields appear only when present", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          task: "Fix the login flow",
          summary: "1 findings: auth (1)",
          detectedFrameworks: ["laravel"],
          results: [makeResult({ level: "high" })],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("- **Report ID:**");
    // Kind value "session_bound" is rendered as "session\_bound" by
    // inlineMarkdown's underscore escape.
    expect(output).toContain("- **Kind:** session\\_bound");
    expect(output).toContain("- **Since:**");
    expect(output).toContain("- **Resolved SHA:**");
    expect(output).toContain("- **Written at:** 2026-01-01T00:00:00Z");
    expect(output).toContain("- **Task:** Fix the login flow");
    expect(output).toContain("- **Frameworks:** laravel");
    expect(output).toContain("- **Risk Level:** HIGH");
    expect(output).toContain("- **Summary:** 1 findings: auth (1)");
  });

  it("omits optional bullets when fields absent; Frameworks renders '(none)' when empty", () => {
    const output = renderMarkdown(makeRenderInput({ file: makeReportFile() }));
    expect(output).not.toContain("**Task:**");
    expect(output).not.toContain("**Summary:**");
    expect(output).not.toContain("**Staged-only:**");
    expect(output).toContain("- **Frameworks:** (none)");
  });
});

// =============================================================================
// SECTION 3: findings
// =============================================================================

describe("renderMarkdown — findings", () => {
  it("empty findings renders 'No findings.' placeholder", () => {
    const output = renderMarkdown(makeRenderInput({ file: makeReportFile() }));
    expect(output).toContain("## Findings");
    expect(output).toContain("No findings.");
  });

  it("single-evidence finding format: **[LEVEL]** title (cat, conf), message, fenced evidence, recommendation", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              category: "auth",
              title: "Auth issue",
              message: "Some message body",
              recommendation: "Fix it.",
              evidence: [{ file: "src/auth.ts", line: 10, detail: "issue detail" }],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("**[HIGH]** Auth issue (auth, medium)");
    expect(output).toContain("Some message body");
    expect(output).toContain("File: src/auth.ts:10");
    expect(output).toContain("Detail: issue detail");
    expect(output).toContain("**Recommendation:** Fix it.");
  });

  it("multi-evidence finding renders all evidence entries inside the fenced block", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              category: "scope-expansion",
              evidence: [
                { file: "a.ts", detail: "overlap: 0.00" },
                { file: "b.ts", detail: "overlap: 0.05" },
              ],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("File: a.ts");
    expect(output).toContain("Detail: overlap: 0.00");
    expect(output).toContain("File: b.ts");
    expect(output).toContain("Detail: overlap: 0.05");
  });

  it("categories rendered as H3 in ASCII-asc order even when engine produces non-alphabetical category order", () => {
    // Engine sort `[level desc, category asc, ...]` produces:
    //   1. critical/payments
    //   2. high/auth
    //   3. high/payments
    // Category first-seen is payments → auth (NOT alphabetical).
    // Markdown renderer must explicitly sort to alphabetical:
    //   ### auth (1 finding)        ← first
    //   ### payments (2 findings)   ← second
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({ level: "critical", category: "payments", id: "c.payments" }),
            makeResult({ level: "high", category: "auth", id: "h.auth" }),
            makeResult({ level: "high", category: "payments", id: "h.payments" }),
          ],
          riskLevel: "critical",
        }),
      }),
    );
    expect(output).toContain("### auth (1 finding)");
    expect(output).toContain("### payments (2 findings)");
    const authIdx = output.indexOf("### auth ");
    const paymentsIdx = output.indexOf("### payments ");
    expect(authIdx).toBeGreaterThan(-1);
    expect(paymentsIdx).toBeGreaterThan(-1);
    expect(authIdx).toBeLessThan(paymentsIdx);
  });
});

// =============================================================================
// SECTION 4: changed files
// =============================================================================

describe("renderMarkdown — changed files", () => {
  it("empty changed_files renders 'No changed files.' placeholder", () => {
    const output = renderMarkdown(makeRenderInput({ file: makeReportFile() }));
    expect(output).toContain("## Changed Files");
    expect(output).toContain("No changed files.");
  });

  it("changed file bullet: `S` path — tags — LEVEL; rename adds (was: ...) suffix", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          changedFiles: [
            {
              path: "src/foo.ts",
              status: "modified",
              risk_tags: ["auth", "middleware"],
              risk_level: "high",
            },
            {
              path: "new-name.ts",
              previous_path: "old-name.ts",
              status: "renamed",
              risk_tags: [],
              risk_level: "low",
            },
          ],
        }),
      }),
    );
    expect(output).toContain("- `M` src/foo.ts — auth, middleware — HIGH");
    expect(output).toContain("- `R` new-name.ts — (no tags) — LOW (was: old-name.ts)");
  });
});

// =============================================================================
// SECTION 5: threshold integration
// =============================================================================

describe("renderMarkdown — threshold integration", () => {
  it("threshold filters results before rendering (low findings disappear at threshold 'high')", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({ level: "low", id: "below", title: "BELOW_THRESHOLD_TITLE" }),
            makeResult({ level: "high", id: "above", title: "ABOVE_THRESHOLD_TITLE" }),
          ],
          riskLevel: "high",
        }),
        threshold: "high",
      }),
    );
    // Sentinel titles contain underscores; inlineMarkdown escapes
    // them so the rendered output contains `ABOVE\_THRESHOLD\_TITLE`.
    // Assertions match the escaped (rendered) form.
    expect(output).toContain("ABOVE\\_THRESHOLD\\_TITLE");
    expect(output).not.toContain("BELOW\\_THRESHOLD\\_TITLE");
  });
});

// =============================================================================
// SECTION 6: locked footer + locked guarantees
// =============================================================================

describe("renderMarkdown — locked footer + guarantees", () => {
  it("renders locked 'Generated by VibeRevert v<version>.' footer using productVersion", () => {
    const output = renderMarkdown(
      makeRenderInput({ file: makeReportFile(), productVersion: "0.7.0-beta" }),
    );
    expect(output).toContain("Generated by VibeRevert v0.7.0-beta.");
  });

  it("output is newline-terminated", () => {
    const output = renderMarkdown(makeRenderInput({ file: makeReportFile() }));
    expect(output.endsWith("\n")).toBe(true);
  });
});

// =============================================================================
// SECTION 7: inline markdown escaping
// =============================================================================

describe("renderMarkdown — inline markdown escaping", () => {
  it("escapes backticks/asterisks/underscores/brackets in user-derived text; evidence content NOT escaped", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          task: "Fix `auth` *flow* with [link]",
          results: [
            makeResult({
              level: "high",
              title: "Title with `backticks`",
              message: "Message with _underscores_",
              evidence: [{ detail: "Evidence with `backticks` not escaped" }],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    // Task: special chars escaped
    expect(output).toContain("\\`auth\\`");
    expect(output).toContain("\\*flow\\*");
    expect(output).toContain("\\[link\\]");
    // Title: backtick escaped
    expect(output).toContain("\\`backticks\\`");
    // Message: underscore escaped
    expect(output).toContain("\\_underscores\\_");
    // Evidence detail: NOT escaped (lives inside fenced block)
    expect(output).toContain("Evidence with `backticks` not escaped");
  });

  it("escapes < and > to HTML entities (no-HTML lock per D45)", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              title: "Title with <script>tag</script>",
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("&lt;script&gt;tag&lt;/script&gt;");
    expect(output).not.toContain("<script>");
  });
});

// =============================================================================
// SECTION 8: dynamic backtick fence
// =============================================================================

describe("renderMarkdown — dynamic backtick fence", () => {
  it("evidence containing triple backticks uses a 4-backtick fence to avoid breakout", () => {
    const output = renderMarkdown(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              evidence: [{ detail: "literal ``` triple backticks inside" }],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    // 4-backtick fence (longer than the 3 inside the evidence).
    expect(output).toContain("````");
    // Evidence content survives verbatim inside the longer fence.
    expect(output).toContain("literal ``` triple backticks inside");
  });
});
