// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Unit tests for packages/reporters/src/receipt-markdown.ts (M D
// Step 5 file 5.7c — receipt markdown-rendering coverage).
//
// Nine test sections covering the receipt-markdown contract:
//
//   1. BANNER — H1 with mode suffix ("(Dry-Run)" for dry-run mode).
//   2. SUMMARY BULLETS — 8 bullets in locked order; inlineCode for
//      IDs/paths (dynamic backtick fence per CommonMark §6.1);
//      schemaToken for enum values (snake_case preserved, no
//      backslash escape); pre-rollback CP placeholder for dry-run.
//   3. WARNINGS — blockquote per warning; blank-line separator
//      between consecutive warnings (REGRESSION GATE against the
//      CommonMark §5.1 blockquote-merge bug caught during 5.4 review).
//   4. FORCED UNRELATED DIRTY PATHS — section ENTIRELY ABSENT when
//      empty; H2 + bulleted inlineCode paths when populated.
//   5. RESULTS — H2; "No results." when empty; bullets with
//      bracketToken outcome + inlineCode path + optional sub-bullet
//      reason; consecutive bullets NOT separated by blank line
//      (CommonMark idiomatic tight list).
//   6. FAILURES — H2; "No failures." when empty; bullets with
//      bracketToken error_code + inlineMarkdown message + optional
//      "Affected paths:" sub-block.
//   7. OUT OF SCOPE — H2 always present; body is
//      inlineMarkdown(file.out_of_scope_notice) — equals
//      ROLLBACK_OUT_OF_SCOPE_NOTICE today since the literal is
//      pure ASCII.
//   8. FOOTER — "Generated by VibeRevert v<version>." paragraph;
//      version IS consumed (unlike terminal); two inputs differing
//      only by version produce DIFFERENT output.
//   9. LOCKED GUARANTEES + REGRESSION GATES — newline-terminated;
//      no GFM/HTML; the three load-bearing regression gates
//      (backtick-in-path dynamic fence, multi-backtick fence
//      escalation, backtick-prefix padding-branch coverage) +
//      token-not-escaped schemaToken protection lives in section 5/6.
//
// Fixture-validity discipline: every fixture flows through
// ReceiptFileSchema.parse via makeReceiptFile, so refine violations
// fail at fixture-construction time. Critical pairings the schema
// enforces (and our fixtures honor):
//   - active_session_warning: true → mode === "dry_run"
//   - dirty_tree_check === "skipped_no_after_state" ↔
//     un_ended_session_warning === true (bidirectional)
//   - forced_unrelated_dirty_paths populated → mode === "apply"
//     + forced === true + dirty_tree_check === "performed"

import {
  RECEIPT_FILE_SCHEMA_VERSION,
  type ReceiptFile,
  ReceiptFileSchema,
  ROLLBACK_OUT_OF_SCOPE_NOTICE,
} from "@viberevert/session-format";
import { describe, expect, it } from "vitest";

import { renderReceiptMarkdown } from "../src/receipt-markdown.js";
import type { ReceiptRenderInput } from "../src/receipt-types.js";

// =============================================================================
// Test fixtures (per-file duplication intentional, matching the
// existing reporter test convention)
// =============================================================================

const VALID_ULID = "01ABCDEFGHJKMNPQRSTVWXYZ23";
const ROLLBACK_ID = `rb_${VALID_ULID}`;
const SESSION_ID = `sess_${VALID_ULID}`;
const CHECKPOINT_ID = `cp_${VALID_ULID}`;

function makeReceiptFile(
  opts: {
    mode?: "dry_run" | "apply";
    forced?: boolean;
    preRollbackCheckpointId?: string | null;
    results?: ReceiptFile["results"];
    failures?: ReceiptFile["failures"];
    forcedUnrelatedDirtyPaths?: readonly string[];
    dirtyTreeCheck?: ReceiptFile["dirty_tree_check"];
    activeSessionWarning?: true;
    unEndedSessionWarning?: true;
  } = {},
): ReceiptFile {
  const mode = opts.mode ?? "apply";
  const preRollbackCp =
    opts.preRollbackCheckpointId !== undefined
      ? opts.preRollbackCheckpointId
      : mode === "apply"
        ? CHECKPOINT_ID
        : null;
  const base = {
    schema_version: RECEIPT_FILE_SCHEMA_VERSION,
    rollback_id: ROLLBACK_ID,
    session_id: SESSION_ID,
    checkpoint_id: CHECKPOINT_ID,
    mode,
    forced: opts.forced ?? false,
    written_at: "2026-01-01T00:00:00Z",
    pre_rollback_checkpoint_id: preRollbackCp,
    results: opts.results ?? [],
    failures: opts.failures ?? [],
    forced_unrelated_dirty_paths: opts.forcedUnrelatedDirtyPaths ?? [],
    dirty_tree_check: opts.dirtyTreeCheck ?? "performed",
    out_of_scope_notice: ROLLBACK_OUT_OF_SCOPE_NOTICE,
  };
  const receipt = {
    ...base,
    ...(opts.activeSessionWarning === true ? { active_session_warning: true as const } : {}),
    ...(opts.unEndedSessionWarning === true ? { un_ended_session_warning: true as const } : {}),
  };
  return ReceiptFileSchema.parse(receipt);
}

function makeRenderInput(opts: { file: ReceiptFile; productVersion?: string }): ReceiptRenderInput {
  return {
    file: opts.file,
    productVersion: opts.productVersion ?? "0.7.0-beta",
  };
}

// =============================================================================
// SECTION 1: banner
// =============================================================================

describe("renderReceiptMarkdown — banner", () => {
  it("apply mode: H1 is '# VibeRevert Rollback Receipt' (no suffix)", () => {
    const file = makeReceiptFile({ mode: "apply" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output.startsWith("# VibeRevert Rollback Receipt\n")).toBe(true);
    expect(output).not.toContain("Dry-Run");
  });

  it("dry-run mode: H1 is '# VibeRevert Rollback Receipt (Dry-Run)' (title-case suffix)", () => {
    const file = makeReceiptFile({ mode: "dry_run" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output.startsWith("# VibeRevert Rollback Receipt (Dry-Run)\n")).toBe(true);
    // Intentional divergence from terminal's "(DRY-RUN)" all-caps.
    expect(output).not.toContain("DRY-RUN");
  });
});

// =============================================================================
// SECTION 2: summary bullets
// =============================================================================

describe("renderReceiptMarkdown — summary bullets", () => {
  it("includes all 8 bullets with locked label text", () => {
    const file = makeReceiptFile({ mode: "apply" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(`- **Rollback ID:** \`${ROLLBACK_ID}\``);
    expect(output).toContain(`- **Session ID:** \`${SESSION_ID}\``);
    expect(output).toContain(`- **Checkpoint ID:** \`${CHECKPOINT_ID}\``);
    expect(output).toContain("- **Mode:** apply");
    expect(output).toContain("- **Forced:** false");
    expect(output).toContain(`- **Pre-rollback CP:** \`${CHECKPOINT_ID}\``);
    expect(output).toContain("- **Dirty-tree check:** performed");
    expect(output).toContain("- **Written at:** 2026-01-01T00:00:00Z");
  });

  it("IDs are wrapped via inlineCode (single-backtick fence on backtick-free inputs)", () => {
    const file = makeReceiptFile({ mode: "apply" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    // Standard ULIDs contain no backticks → fence = 1 backtick.
    expect(output).toContain(`\`${ROLLBACK_ID}\``);
    expect(output).toContain(`\`${SESSION_ID}\``);
    expect(output).toContain(`\`${CHECKPOINT_ID}\``);
  });

  it("dry-run pre-rollback CP renders as '(none - dry-run)' placeholder (NO code span)", () => {
    const file = makeReceiptFile({ mode: "dry_run" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **Pre-rollback CP:** (none - dry-run)");
    // The placeholder is plain text, not a code span — no surrounding backticks.
    expect(output).not.toContain("`(none - dry-run)`");
  });

  it("Mode and Dirty-tree check render via schemaToken (raw enum, no backslash escape)", () => {
    // The load-bearing assertion: snake_case values stay grep-able.
    // Per D69 bidirectional coupling, dirty_tree_check ===
    // "skipped_no_after_state" REQUIRES un_ended_session_warning ===
    // true. Including it here keeps the fixture schema-valid and
    // also semantically honest — "skipped after-state" should
    // always carry the warning.
    const file = makeReceiptFile({
      mode: "dry_run",
      dirtyTreeCheck: "skipped_no_after_state",
      unEndedSessionWarning: true,
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **Mode:** dry_run");
    expect(output).toContain("- **Dirty-tree check:** skipped_no_after_state");
    expect(output).not.toContain("dry\\_run");
    expect(output).not.toContain("skipped\\_no\\_after\\_state");
  });

  it("summary bullet order is locked (indexOf monotonicity check)", () => {
    const file = makeReceiptFile({ mode: "apply" });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    const labels = [
      "- **Rollback ID:**",
      "- **Session ID:**",
      "- **Checkpoint ID:**",
      "- **Mode:**",
      "- **Forced:**",
      "- **Pre-rollback CP:**",
      "- **Dirty-tree check:**",
      "- **Written at:**",
    ];
    let lastIdx = -1;
    for (const label of labels) {
      const idx = output.indexOf(label);
      expect(idx).toBeGreaterThan(lastIdx);
      lastIdx = idx;
    }
  });
});

// =============================================================================
// SECTION 3: warnings
// =============================================================================

describe("renderReceiptMarkdown — warnings", () => {
  it("both warnings absent: no '> **Warning:**' blockquote lines emitted", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).not.toContain("> **Warning:**");
  });

  it("only active_session_warning set: only the active-session blockquote is emitted", () => {
    const file = makeReceiptFile({ mode: "dry_run", activeSessionWarning: true });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(
      "> **Warning:** Active session - apply mode would refuse on this session.",
    );
    expect(output).not.toContain("> **Warning:** No machine-readable after-status snapshot");
  });

  it("only un_ended_session_warning set: only the un-ended blockquote is emitted", () => {
    const file = makeReceiptFile({
      mode: "dry_run",
      dirtyTreeCheck: "skipped_no_after_state",
      unEndedSessionWarning: true,
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(
      "> **Warning:** No machine-readable after-status snapshot for this session.",
    );
    expect(output).not.toContain("> **Warning:** Active session");
  });

  it("REGRESSION GATE: dual warnings render as two distinct blockquote blocks (blank line between)", () => {
    // Per CommonMark §5.1, consecutive `>` lines without an
    // intervening blank line form ONE blockquote block. The
    // implementation inserts a blank line between warnings so they
    // render as DISTINCT blocks. A regression that dropped the
    // blank-line separator would merge both warnings into one
    // wrapped paragraph in most renderers — locked behavior worth
    // pinning explicitly so a future "simplify the buildWarnings
    // logic" refactor can't silently weaken it.
    const file = makeReceiptFile({
      mode: "dry_run",
      dirtyTreeCheck: "skipped_no_after_state",
      activeSessionWarning: true,
      unEndedSessionWarning: true,
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(
      "> **Warning:** Active session - apply mode would refuse on this session.\n\n> **Warning:** No machine-readable after-status snapshot for this session.",
    );
  });
});

// =============================================================================
// SECTION 4: forced unrelated dirty paths
// =============================================================================

describe("renderReceiptMarkdown — forced unrelated dirty paths section", () => {
  it("empty: section is ENTIRELY ABSENT (no H2, no list)", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).not.toContain("## Forced Unrelated Dirty Paths");
  });

  it("populated: H2 'Forced Unrelated Dirty Paths' + bulleted inlineCode paths", () => {
    // forced_unrelated_dirty_paths is only schema-valid when
    // mode: "apply" + forced: true + dirty_tree_check: "performed".
    const file = makeReceiptFile({
      mode: "apply",
      forced: true,
      dirtyTreeCheck: "performed",
      forcedUnrelatedDirtyPaths: ["src/dirty-a.ts", "src/dirty-b.ts"],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("## Forced Unrelated Dirty Paths");
    expect(output).toContain("- `src/dirty-a.ts`");
    expect(output).toContain("- `src/dirty-b.ts`");
  });

  it("single path: still rendered as a single-item list", () => {
    const file = makeReceiptFile({
      mode: "apply",
      forced: true,
      dirtyTreeCheck: "performed",
      forcedUnrelatedDirtyPaths: ["src/only.ts"],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("## Forced Unrelated Dirty Paths");
    expect(output).toContain("- `src/only.ts`");
  });
});

// =============================================================================
// SECTION 5: results
// =============================================================================

describe("renderReceiptMarkdown — results section", () => {
  it("empty results: H2 followed by 'No results.' paragraph", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("## Results\n\nNo results.");
  });

  it("single result without reason: '- **[OUTCOME]** `path`' bullet, no sub-bullet", () => {
    const file = makeReceiptFile({
      results: [{ path: "src/foo.ts", outcome: "tracked_restored" }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[TRACKED_RESTORED]** `src/foo.ts`");
    expect(output).not.toContain("  - Reason:");
  });

  it("single result with reason: bullet + sub-bullet 'Reason: ...' (2-space indent)", () => {
    const file = makeReceiptFile({
      results: [
        {
          path: "src/foo.ts",
          outcome: "skipped_excluded",
          reason: "matches rollback.exclude pattern test.ts",
        },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[SKIPPED_EXCLUDED]** `src/foo.ts`");
    expect(output).toContain("  - Reason: matches rollback.exclude pattern test.ts");
  });

  it("multiple results: bullets are consecutive WITHOUT blank line between (CommonMark tight list)", () => {
    // Unlike terminal which inserts blank-line separators, markdown
    // packs consecutive bullets into a tight list per CommonMark
    // convention. A regression that inserted blank lines would
    // produce a loose list with extra paragraph spacing.
    const file = makeReceiptFile({
      results: [
        { path: "src/a.ts", outcome: "tracked_restored" },
        { path: "src/b.ts", outcome: "untracked_restored" },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(
      "- **[TRACKED_RESTORED]** `src/a.ts`\n- **[UNTRACKED_RESTORED]** `src/b.ts`",
    );
  });

  it("REGRESSION GATE: outcome token via schemaToken is RAW snake_case (NOT inlineMarkdown-escaped)", () => {
    // A regression that reverts schemaToken → inlineMarkdown would
    // escape every underscore as `\_`, producing
    // **[TRACKED\_RESTORED]** in the rendered source — polluting
    // grep-ability and contradicting the receipt-markdown.ts layout
    // lock. This test catches that regression at the source-bytes
    // level via both targeted and broad substring checks.
    const file = makeReceiptFile({
      results: [{ path: "src/foo.ts", outcome: "tracked_restored" }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("**[TRACKED_RESTORED]**");
    expect(output).not.toContain("**[TRACKED\\_RESTORED]**");
    expect(output).not.toContain("TRACKED\\_RESTORED");
  });
});

// =============================================================================
// SECTION 6: failures
// =============================================================================

describe("renderReceiptMarkdown — failures section", () => {
  it("empty failures: H2 followed by 'No failures.' paragraph", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("## Failures\n\nNo failures.");
  });

  it("single failure without affected_paths: '- **[ERROR_CODE]** message' bullet, no sub-block", () => {
    const file = makeReceiptFile({
      failures: [
        {
          error_code: "internal",
          message: "unexpected null in restore plan",
          affected_paths: [],
        },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[INTERNAL]** unexpected null in restore plan");
    expect(output).not.toContain("  - Affected paths:");
  });

  it("single failure with affected_paths: bullet + 'Affected paths:' sub-bullet + nested inlineCode bullets (4-space indent)", () => {
    const file = makeReceiptFile({
      failures: [
        {
          error_code: "extraction_conflict",
          message: "tarball entry would overwrite tracked file",
          affected_paths: ["src/conflict-a.ts", "src/conflict-b.ts"],
        },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(
      "- **[EXTRACTION_CONFLICT]** tarball entry would overwrite tracked file",
    );
    expect(output).toContain("  - Affected paths:");
    expect(output).toContain("    - `src/conflict-a.ts`");
    expect(output).toContain("    - `src/conflict-b.ts`");
  });

  it("REGRESSION GATE: error_code token via schemaToken is RAW snake_case (NOT inlineMarkdown-escaped)", () => {
    const file = makeReceiptFile({
      failures: [
        {
          error_code: "tracked_dirty_parity",
          message: "tracked dirty paths do not match manifest",
          affected_paths: [],
        },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("**[TRACKED_DIRTY_PARITY]**");
    expect(output).not.toContain("**[TRACKED\\_DIRTY\\_PARITY]**");
    expect(output).not.toContain("TRACKED\\_DIRTY\\_PARITY");
  });
});

// =============================================================================
// SECTION 7: out of scope
// =============================================================================

describe("renderReceiptMarkdown — out of scope section", () => {
  it("section H2 is always present even on minimal receipt", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("## Out of Scope");
  });

  it("body is file.out_of_scope_notice escaped via inlineMarkdown (no-op for the pure-ASCII literal)", () => {
    // The current ROLLBACK_OUT_OF_SCOPE_NOTICE is pure ASCII prose
    // with no markdown-active characters, so inlineMarkdown is a
    // no-op and the rendered output equals the literal verbatim.
    // A future schema-literal change introducing markdown chars
    // would break this test — at which point the assertion should
    // be updated to compare against the escaped form.
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain(ROLLBACK_OUT_OF_SCOPE_NOTICE);
  });
});

// =============================================================================
// SECTION 8: footer
// =============================================================================

describe("renderReceiptMarkdown — footer", () => {
  it("emits 'Generated by VibeRevert v<version>.' as the final paragraph", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file, productVersion: "0.7.0-beta" }));
    expect(output).toContain("Generated by VibeRevert v0.7.0-beta.");
  });

  it("two inputs differing only by productVersion produce DIFFERENT output (footer consumes it)", () => {
    // Unlike terminal (which ignores productVersion entirely),
    // markdown bakes productVersion into the locked footer. Two
    // outputs MUST diverge — opposite invariant from the terminal
    // test's "byte-identical regardless of version" lock.
    const file = makeReceiptFile();
    const a = renderReceiptMarkdown(makeRenderInput({ file, productVersion: "0.7.0-beta" }));
    const b = renderReceiptMarkdown(makeRenderInput({ file, productVersion: "999.999.999-fake" }));
    expect(a).not.toBe(b);
    expect(a).toContain("0.7.0-beta");
    expect(b).toContain("999.999.999-fake");
  });

  it("productVersion is escaped via inlineMarkdown (defense against future version-string injection)", () => {
    // A productVersion containing markdown-active characters
    // (`*`, `_`, `` ` ``, brackets) must be escaped to prevent
    // emphasis/code/link formation in the footer paragraph. Today
    // productVersion comes from package.json and is trusted, but
    // the renderer escapes defensively per the same rule applied
    // to every other prose value.
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(
      makeRenderInput({ file, productVersion: "1.0.0-*alpha*" }),
    );
    // Asterisks should be backslash-escaped → "1.0.0-\*alpha\*"
    expect(output).toContain("Generated by VibeRevert v1.0.0-\\*alpha\\*.");
    expect(output).not.toContain("VibeRevert v1.0.0-*alpha*.");
  });
});

// =============================================================================
// SECTION 9: locked guarantees + regression gates
// =============================================================================

describe("renderReceiptMarkdown — locked guarantees", () => {
  it("output is newline-terminated", () => {
    const file = makeReceiptFile();
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output.endsWith("\n")).toBe(true);
  });

  it("REGRESSION GATE: path containing one backtick uses a 2-backtick fence", () => {
    // inlineCode picks fence length = longest backtick run + 1.
    // Path "src/weird`name.ts" has a single backtick → fence = 2.
    // Output: `- **[TRACKED_RESTORED]** ``src/weird`name.ts``` (2 fences around content with 1 backtick inside).
    // A regression to the unsafe `\`${inlineMarkdown(path)}\`` pattern
    // would either break the code span (escape doesn't work in
    // code spans per CommonMark §6.1) or render visible backslash
    // literals.
    const file = makeReceiptFile({
      results: [{ path: "src/weird`name.ts", outcome: "tracked_restored" }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[TRACKED_RESTORED]** ``src/weird`name.ts``");
  });

  it("REGRESSION GATE: path containing a two-backtick run escalates fence to 3 backticks", () => {
    // Locks the dynamic-fence-length logic beyond the single-backtick
    // case. Path "src/double``name.ts" has 2 consecutive backticks
    // → fence = 3.
    const file = makeReceiptFile({
      results: [{ path: "src/double``name.ts", outcome: "tracked_restored" }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[TRACKED_RESTORED]** ```src/double``name.ts```");
  });

  it("REGRESSION GATE: path beginning with a backtick uses padded inline-code content", () => {
    // Locks the `needsPadding` branch of inlineCode. Without
    // padding, content beginning with a backtick would merge with
    // the opening fence in CommonMark's parser — the 2-backtick
    // fence + leading backtick content would be read as a
    // 3-backtick delimiter, breaking the span. The space-padded
    // form `` `leading.ts `` parses correctly because the parser
    // strips one leading + one trailing space when both boundaries
    // have a space (per CommonMark §6.1).
    //
    // The other backtick regression tests use paths with backticks
    // in the MIDDLE — they don't exercise this padding branch and
    // would still pass under a regression that deleted the padding
    // logic entirely. This test is what catches that specific
    // regression class.
    const file = makeReceiptFile({
      results: [{ path: "`leading.ts", outcome: "tracked_restored" }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).toContain("- **[TRACKED_RESTORED]** `` `leading.ts ``");
  });

  it("NO raw HTML angle brackets in the output (D45 no-HTML lock)", () => {
    // inlineMarkdown HTML-encodes `<` and `>` so user-derived prose
    // can't form raw HTML. The schema-controlled fields (mode,
    // outcome, etc.) never contain angle brackets in practice, but
    // a reason or message with embedded `<script>` would be safely
    // escaped to `&lt;script&gt;`.
    const file = makeReceiptFile({
      results: [
        {
          path: "src/foo.ts",
          outcome: "tracked_restored",
          reason: "test <script>alert('xss')</script>",
        },
      ],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).not.toContain("<script>");
    expect(output).toContain("&lt;script&gt;");
  });

  it("NO GFM table syntax (`| --- |` pipes-and-dashes) in the output (D45 lock)", () => {
    // The CommonMark-only lock forbids GFM table extensions. A
    // future "let's render results as a markdown table" temptation
    // would surface here.
    const file = makeReceiptFile({
      results: [{ path: "src/foo.ts", outcome: "tracked_restored" }],
      failures: [{ error_code: "verification", message: "test", affected_paths: ["src/bar.ts"] }],
    });
    const output = renderReceiptMarkdown(makeRenderInput({ file }));
    expect(output).not.toMatch(/\|\s*---+\s*\|/);
  });
});
