// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fabio Marcello Salvadori

// Unit tests for packages/reporters/src/terminal.ts
// (Step 8 Phase C file 15).
//
// Coverage strategy:
//
//   1. HEADER — required fields appear; staged_only / task / summary
//      shown only when present; frameworks "(none)" when empty.
//
//   2. FINDINGS — empty section renders "(none)" placeholder;
//      single-evidence finding has File/Detail/Recommendation lines;
//      multi-evidence finding has "Evidence:" indent list;
//      Message: line always rendered after title (no information
//      loss from CheckResult.message); Recommendation omitted when
//      absent or empty.
//
//   3. CHANGED FILES — empty section renders "(none)"; row format
//      "S  path  [tags]  LEVEL"; rename status adds "(was: ...)";
//      empty tags array renders as "[]".
//
//   4. THRESHOLD INTEGRATION — applyThreshold is called before
//      rendering; low findings disappear when threshold "high".
//
//   5. LOCKED GUARANTEES — no "Generated by VibeRevert" footer in
//      terminal output (D45 markdown-only lock); productVersion
//      not consumed; output is newline-terminated; ANSI-free
//      (no escape codes in output).

import type {
  ChangedFile,
  CheckResult,
  ReportFile,
  RiskLevel,
  SessionReport,
} from "@viberevert/session-format";
import { describe, expect, it } from "vitest";

import type { RenderInput } from "../src/index.js";
import { renderTerminal } from "../src/terminal.js";

// =============================================================================
// Test fixture helpers
// =============================================================================

const VALID_ULID = "01ABCDEFGHJKMNPQRSTVWXYZ23";
const SESSION_ID = `sess_${VALID_ULID}`;
const REPORT_ID = `rpt_${VALID_ULID}`;

function makeResult(opts: {
  level: RiskLevel;
  category?: string;
  id?: string;
  title?: string;
  message?: string;
  recommendation?: string;
  evidence?: readonly { file?: string; line?: number; command?: string; detail: string }[];
}): CheckResult {
  const requiresReco = opts.level === "high" || opts.level === "critical";
  const reco = opts.recommendation ?? (requiresReco ? "Test recommendation." : undefined);
  const evidence = opts.evidence ?? [{ detail: "test detail" }];
  const base = {
    id: opts.id ?? "test.id",
    category: opts.category ?? "test",
    level: opts.level,
    confidence: "medium" as const,
    title: opts.title ?? "Test title",
    message: opts.message ?? "Test message",
    evidence: [...evidence],
  };
  return reco === undefined ? base : { ...base, recommendation: reco };
}

function makeReportFile(
  opts: {
    results?: readonly CheckResult[];
    summary?: string;
    riskLevel?: RiskLevel;
    task?: string;
    detectedFrameworks?: readonly string[];
    changedFiles?: readonly ChangedFile[];
  } = {},
): ReportFile {
  const reportBase: SessionReport = {
    schema_version: "1.0",
    session_id: SESSION_ID,
    started_at: "2026-01-01T00:00:00Z",
    detected_frameworks: [...(opts.detectedFrameworks ?? [])],
    risk_level: opts.riskLevel ?? "low",
    results: [...(opts.results ?? [])],
    changed_files: [...(opts.changedFiles ?? [])],
    rollback_available: true,
  };
  const report: SessionReport = {
    ...reportBase,
    ...(opts.summary !== undefined ? { summary: opts.summary } : {}),
    ...(opts.task !== undefined ? { task: opts.task } : {}),
  };
  return {
    schema_version: "1.0",
    kind: "session_bound",
    report_id: SESSION_ID,
    since_kind: "session_id",
    since_ref: SESSION_ID,
    since_resolved_sha: "0000000000000000000000000000000000000000",
    written_at: "2026-01-01T00:00:00Z",
    report,
  };
}

/**
 * Construct an ad_hoc ReportFile (used by tests that need
 * staged_only: true, which the schema gates on kind === "ad_hoc").
 */
function makeAdHocReportFile(
  opts: { stagedOnly?: true; results?: readonly CheckResult[]; riskLevel?: RiskLevel } = {},
): ReportFile {
  const report: SessionReport = {
    schema_version: "1.0",
    session_id: REPORT_ID,
    started_at: "2026-01-01T00:00:00Z",
    detected_frameworks: [],
    risk_level: opts.riskLevel ?? "low",
    results: [...(opts.results ?? [])],
    changed_files: [],
    rollback_available: false,
  };
  const base = {
    schema_version: "1.0" as const,
    kind: "ad_hoc" as const,
    report_id: REPORT_ID,
    since_kind: "git_ref" as const,
    since_ref: "HEAD",
    since_resolved_sha: "0000000000000000000000000000000000000000",
    written_at: "2026-01-01T00:00:00Z",
    report,
  };
  return opts.stagedOnly === true ? { ...base, staged_only: true } : base;
}

function makeRenderInput(opts: {
  file: ReportFile;
  threshold?: RiskLevel;
  productVersion?: string;
}): RenderInput {
  const base = { file: opts.file, productVersion: opts.productVersion ?? "0.7.0-beta" };
  return opts.threshold === undefined ? base : { ...base, threshold: opts.threshold };
}

// =============================================================================
// SECTION 1: header
// =============================================================================

describe("renderTerminal — header", () => {
  it("renders required header fields", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({ detectedFrameworks: ["laravel", "nextjs"] }),
      }),
    );
    expect(output).toContain("VibeRevert Report");
    expect(output).toContain("Report ID:");
    expect(output).toContain(SESSION_ID);
    expect(output).toContain("Kind:");
    expect(output).toContain("session_bound");
    expect(output).toContain("Since:");
    expect(output).toContain("Resolved SHA:");
    expect(output).toContain("Written at:");
    expect(output).toContain("2026-01-01T00:00:00Z");
    expect(output).toContain("Frameworks:   laravel, nextjs");
    expect(output).toContain("Risk Level:");
  });

  it("staged_only line appears only when present (ad_hoc file)", () => {
    const withStaged = renderTerminal(
      makeRenderInput({ file: makeAdHocReportFile({ stagedOnly: true }) }),
    );
    expect(withStaged).toContain("Staged-only:  true");

    const withoutStaged = renderTerminal(makeRenderInput({ file: makeAdHocReportFile() }));
    expect(withoutStaged).not.toContain("Staged-only");
  });

  it("Task line appears only when present", () => {
    const withTask = renderTerminal(
      makeRenderInput({ file: makeReportFile({ task: "Fix the login flow" }) }),
    );
    expect(withTask).toContain("Task:         Fix the login flow");

    const withoutTask = renderTerminal(makeRenderInput({ file: makeReportFile() }));
    expect(withoutTask).not.toContain("Task:");
  });

  it("Summary line appears only when present; Frameworks '(none)' when empty", () => {
    const withSummary = renderTerminal(
      makeRenderInput({
        file: makeReportFile({ summary: "1 findings: test (1)" }),
      }),
    );
    expect(withSummary).toContain("Summary:      1 findings: test (1)");

    const withoutSummaryNoFrameworks = renderTerminal(makeRenderInput({ file: makeReportFile() }));
    expect(withoutSummaryNoFrameworks).not.toContain("Summary:");
    expect(withoutSummaryNoFrameworks).toContain("Frameworks:   (none)");
  });
});

// =============================================================================
// SECTION 2: findings
// =============================================================================

describe("renderTerminal — findings", () => {
  it("empty findings renders '(none)' placeholder under 'Findings (0)' heading", () => {
    const output = renderTerminal(makeRenderInput({ file: makeReportFile() }));
    expect(output).toContain("Findings (0)");
    expect(output).toContain("(none)");
  });

  it("single-evidence finding renders title, Message, File, Detail, Recommendation lines", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              category: "auth",
              title: "Risky auth change",
              message: "Changes to AuthMiddleware.php were not paired with a sibling test",
              recommendation: "Add or update sibling tests.",
              evidence: [
                {
                  file: "app/Http/Middleware/AuthMiddleware.php",
                  line: 42,
                  detail: "path-rule: laravel.middleware",
                },
              ],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("[HIGH] auth: Risky auth change");
    expect(output).toContain(
      "  Message: Changes to AuthMiddleware.php were not paired with a sibling test",
    );
    expect(output).toContain("  File: app/Http/Middleware/AuthMiddleware.php:42");
    expect(output).toContain("  Detail: path-rule: laravel.middleware");
    expect(output).toContain("  Recommendation: Add or update sibling tests.");
  });

  it("multi-evidence finding renders 'Evidence:' indent list", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({
              level: "high",
              category: "scope-expansion",
              title: "Scope expansion: auth",
              evidence: [
                { file: "app/Http/Middleware/AuthMiddleware.php", detail: "overlap: 0.00" },
                { file: "app/Http/Middleware/CsrfMiddleware.php", detail: "overlap: 0.00" },
              ],
            }),
          ],
          riskLevel: "high",
        }),
      }),
    );
    expect(output).toContain("[HIGH] scope-expansion: Scope expansion: auth");
    expect(output).toContain("  Evidence:");
    expect(output).toContain("    - app/Http/Middleware/AuthMiddleware.php (overlap: 0.00)");
    expect(output).toContain("    - app/Http/Middleware/CsrfMiddleware.php (overlap: 0.00)");
  });

  it("Recommendation line OMITTED when recommendation is absent or empty", () => {
    // low/medium findings don't require recommendation; build one
    // explicitly without it.
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          results: [makeResult({ level: "low", category: "test" })],
        }),
      }),
    );
    expect(output).toContain("[LOW] test: Test title");
    expect(output).not.toContain("Recommendation:");
  });
});

// =============================================================================
// SECTION 3: changed files
// =============================================================================

describe("renderTerminal — changed files", () => {
  it("empty changed_files renders '(none)' placeholder under 'Changed Files (0)' heading", () => {
    const output = renderTerminal(makeRenderInput({ file: makeReportFile() }));
    expect(output).toContain("Changed Files (0)");
  });

  it("changed file row uses status code + path + tags + UPPERCASE level", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          changedFiles: [
            {
              path: "app/Http/Middleware/AuthMiddleware.php",
              status: "modified",
              risk_tags: ["auth", "middleware"],
              risk_level: "high",
            },
          ],
        }),
      }),
    );
    expect(output).toContain("M  app/Http/Middleware/AuthMiddleware.php  [auth, middleware]  HIGH");
  });

  it("renamed file row appends '(was: <previous_path>)' suffix; empty tags render as '[]'", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          changedFiles: [
            {
              path: "new-name.ts",
              previous_path: "old-name.ts",
              status: "renamed",
              risk_tags: [],
              risk_level: "low",
            },
          ],
        }),
      }),
    );
    expect(output).toContain("R  new-name.ts  []  LOW  (was: old-name.ts)");
  });
});

// =============================================================================
// SECTION 4: threshold integration
// =============================================================================

describe("renderTerminal — threshold integration", () => {
  it("threshold filters results before rendering (low findings disappear at threshold 'high')", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          results: [
            makeResult({ level: "low", id: "below.threshold", title: "BELOW_THRESHOLD_TITLE" }),
            makeResult({ level: "high", id: "above.threshold", title: "ABOVE_THRESHOLD_TITLE" }),
          ],
          riskLevel: "high",
        }),
        threshold: "high",
      }),
    );
    expect(output).toContain("ABOVE_THRESHOLD_TITLE");
    expect(output).not.toContain("BELOW_THRESHOLD_TITLE");
    expect(output).toContain("Findings (1)");
  });
});

// =============================================================================
// SECTION 5: locked guarantees
// =============================================================================

describe("renderTerminal — locked guarantees", () => {
  it("NO 'Generated by VibeRevert' footer (markdown-only per D45)", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile(),
        productVersion: "999.999.999-fake",
      }),
    );
    expect(output).not.toContain("Generated by VibeRevert");
    expect(output).not.toContain("999.999.999-fake");
  });

  it("productVersion NOT consumed — two outputs differing only by productVersion are identical", () => {
    const file = makeReportFile({
      results: [makeResult({ level: "high" })],
      riskLevel: "high",
    });
    const a = renderTerminal(makeRenderInput({ file, productVersion: "0.7.0-beta" }));
    const b = renderTerminal(makeRenderInput({ file, productVersion: "999.999.999-fake" }));
    expect(a).toBe(b);
  });

  it("output is newline-terminated", () => {
    const output = renderTerminal(makeRenderInput({ file: makeReportFile() }));
    expect(output.endsWith("\n")).toBe(true);
  });

  it("output is ANSI-free (no escape codes)", () => {
    const output = renderTerminal(
      makeRenderInput({
        file: makeReportFile({
          results: [makeResult({ level: "critical", title: "X", recommendation: "Y" })],
          riskLevel: "critical",
          summary: "1 findings: test (1)",
        }),
      }),
    );
    // ANSI escape sequence starts with ESC (\x1b) followed by [.
    // biome-ignore lint/suspicious/noControlCharactersInRegex: locked detection regex
    expect(output).not.toMatch(/\x1b\[/);
  });
});
